//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface _PTHWORMData : NSData
{
    unsigned long long _pageSize;
    unsigned long long _length;
    unsigned long long _currentOffset;
    unsigned long long _writeBlockSize;
    unsigned long long _padSize;
    struct _NSRange _writeRange;
    int _fd;
    void *_map;
}

@property(readonly, nonatomic) unsigned long long currentOffset; // @synthesize currentOffset=_currentOffset;
- (void)dealloc;
- (void)sync;
- (id)subdataWithRange:(struct _NSRange)arg1;
- (long long)appendData:(id)arg1;
- (const void *)bytes;
- (unsigned long long)length;
- (id)initWithPath:(id)arg1 length:(unsigned long long)arg2 currentOffset:(unsigned long long)arg3 padSize:(unsigned long long)arg4;

@end

