//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class ACAccount, UIImageView, UILabel;

@interface _PTHTweetbotLaunchAccountView : UIControl
{
    UIImageView *_checkmarkView;
    UILabel *_nameLabel;
    ACAccount *_account;
}

@property(retain, nonatomic) ACAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)_updateState;
- (id)initWithFrame:(struct CGRect)arg1;

@end

