//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHButton.h"

@class PTHTweetbotList;

@interface _PTHTweetbotListPickerListView : PTHButton
{
    PTHTweetbotList *_list;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(readonly, nonatomic) PTHTweetbotList *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (id)initWithList:(id)arg1;

@end

