//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHColorGroupTableViewCell.h"

@class PTHTweetbotList, UIImageView;

@interface _PTHTweetbotManageListMembershipsCell : PTHColorGroupTableViewCell
{
    UIImageView *_lockView;
    UIImageView *_checkmarkView;
    id _listObserver;
    PTHTweetbotList *_list;
}

@property(retain, nonatomic) PTHTweetbotList *list; // @synthesize list=_list;
- (void).cxx_destruct;
@property(nonatomic) _Bool listSelected;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

