//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISlider.h"

@interface _PTHSteppedSlider : UISlider
{
}

- (void)setValue:(float)arg1 animated:(_Bool)arg2;
- (void)setBounds:(struct CGRect)arg1;
- (void)colorThemeDidChange;
- (void)setEnabled:(_Bool)arg1;
- (void)updateTrackImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

