//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class PTHTweetbotPostDraftMedium, UIImageView;

@interface _PTHTweetbotPostMediaThumbnailView : UIControl
{
    UIImageView *_imageView;
    UIImageView *_playImageView;
    _Bool _loaded;
    PTHTweetbotPostDraftMedium *_medium;
}

@property(nonatomic, getter=isLoaded) _Bool loaded; // @synthesize loaded=_loaded;
@property(retain, nonatomic) PTHTweetbotPostDraftMedium *medium; // @synthesize medium=_medium;
- (void).cxx_destruct;
- (void)setMedium:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)colorThemeDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

