//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSLayoutConstraint, PTHTweetbotAvatarView, UIImageView, UILabel, UIView;

@interface _PTHTweetbotPostToolbarResultsCell : UIControl
{
    UIView *_leftLine;
    UIView *_rightLine;
    _Bool _widthCell;
    id _result;
    NSLayoutConstraint *_textLeftConstraint;
    UILabel *_textLabel;
    UILabel *_detailTextLabel;
    PTHTweetbotAvatarView *_avatarView;
    UIImageView *_imageView;
}

+ (double)widthForResult:(id)arg1;
+ (id)entityTextForResult:(id)arg1;
@property(nonatomic) _Bool widthCell; // @synthesize widthCell=_widthCell;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) PTHTweetbotAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UILabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) NSLayoutConstraint *textLeftConstraint; // @synthesize textLeftConstraint=_textLeftConstraint;
@property(retain, nonatomic) id result; // @synthesize result=_result;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (id)initWithFrame:(struct CGRect)arg1;

@end

