//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface _PTHMaskedImageView : UIImageView
{
    _Bool _maskToBackground;
}

@property(nonatomic) _Bool maskToBackground; // @synthesize maskToBackground=_maskToBackground;
- (void)_updateImageMask;
- (void)setBounds:(struct CGRect)arg1;
- (void)setImage:(id)arg1;

@end

