//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSRegularExpression, NSString;

@interface _PTHTweetbotRegexMediaParserItem : NSObject
{
    NSString *_expressionString;
    NSDictionary *_previewFormats;
    NSString *_mediaFormat;
    NSRegularExpression *_expression;
    NSArray *_hosts;
    long long _mediumType;
}

@property(readonly, nonatomic) long long mediumType; // @synthesize mediumType=_mediumType;
@property(readonly, nonatomic) NSArray *hosts; // @synthesize hosts=_hosts;
- (void).cxx_destruct;
- (_Bool)hasPreviewURLs;
- (id)previewURLDictionaryForURL:(id)arg1;
- (id)mediumURLForURL:(id)arg1;
- (id)_url:(id)arg1 withFormat:(id)arg2;
- (_Bool)canParseURL:(id)arg1;
- (id)expression;
- (id)initWithDictionary:(id)arg1;

@end

