//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMapViewController.h"

@class MKPlacemark;

@interface _PTHTweetbotGeoMapViewController : PTHTweetbotMapViewController
{
    MKPlacemark *_annotation;
}

- (void).cxx_destruct;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (void)viewDidLoad;

@end

