//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class PTHTweetbotEntity;

@interface _PTHTweetbotPhoneProfilePhotosBlockView : UIControl
{
    PTHTweetbotEntity *_entity;
}

@property(retain, nonatomic) PTHTweetbotEntity *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (id)initWithEntity:(id)arg1;

@end

