//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPopoverBackgroundView.h"

@class UIImageView;

@interface _PTHPopoverBackgroundView : UIPopoverBackgroundView
{
    UIImageView *_side1PartialView;
    double _side1MinSize;
    UIImageView *_side2PartialView;
    double _side2MinSize;
    UIImageView *_centerView;
    UIImageView *_side1FullView;
    UIImageView *_side2FullView;
    UIImageView *_overlayFrameView;
    unsigned long long _arrowDirection;
    double _arrowOffset;
}

+ (struct UIEdgeInsets)contentViewInsets;
+ (double)arrowBase;
+ (double)arrowHeight;
@property(nonatomic) double arrowOffset; // @synthesize arrowOffset=_arrowOffset;
@property(nonatomic) unsigned long long arrowDirection; // @synthesize arrowDirection=_arrowDirection;
- (void).cxx_destruct;
- (void)willMoveToWindow:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

