//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (PTHNSArrayCategory)
- (id)editActionsForIdenticalObjectsToArray:(id)arg1;
- (id)editActionsToArray:(id)arg1;
- (id)arrayByMergingWithArray:(id)arg1;
- (_Bool)hasSuffix:(id)arg1;
- (_Bool)hasPrefix:(id)arg1;
- (id)arrayByEnumeratingBlock:(CDUnknownBlockType)arg1;
- (id)objectsPassingTest:(CDUnknownBlockType)arg1;
- (id)objectPassingTest:(CDUnknownBlockType)arg1;
- (id)arrayByPerformingSelector:(SEL)arg1;
- (id)reversedArray;
- (unsigned long long)deepHash;
@end

