//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (PTHNSDataCategory)
- (id)sha1Data;
- (id)imageMimeType;
- (id)imageUTType;
- (_Bool)isBMPData;
- (_Bool)isICNSData;
- (_Bool)isJPEG2000Data;
- (_Bool)isTIFFData;
- (_Bool)isGIFData;
- (_Bool)isJPEGData;
- (_Bool)isPNGData;
- (id)decryptAES256:(id)arg1;
- (id)encryptAES256:(id)arg1;
- (id)hexString;
@end

