//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (PTHNSFileManagerCategory)
- (unsigned long long)fileSizeAtURL:(id)arg1;
- (void)resetCloud;
- (_Bool)addSkipBackupAttributeToItemAtPath:(id)arg1;
- (_Bool)addSkipBackupAttributeToItemAtURL:(id)arg1;
@end

