//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableAttributedString.h"

@interface NSMutableAttributedString (PTHNSMutableAttributedStringCategory)
- (void)processTag:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)processMarkdown;
- (void)setAttribute:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;
@end

