//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (PTHNSObjectCategory)
+ (_Bool)runIfLastTimeWasAtLeast:(double)arg1 identifier:(id)arg2 persistent:(_Bool)arg3 block:(CDUnknownBlockType)arg4;
+ (void)resetLastRunTime:(id)arg1;
+ (_Bool)replaceClassMethod:(SEL)arg1 withClassMethod:(SEL)arg2;
+ (_Bool)replaceMethod:(SEL)arg1 withMethod:(SEL)arg2;
- (void)listenToNotificationName:(id)arg1 object:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)addDeallocBlock:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1 forKeyPaths:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPaths:(id)arg2;
- (id)associatedObjectForKey:(const void *)arg1;
- (void)setAssociatedCopiedObject:(id)arg1 forKey:(const void *)arg2;
- (void)setAssociatedNonRetainedObject:(id)arg1 forKey:(const void *)arg2;
- (void)setAssociatedObject:(id)arg1 forKey:(const void *)arg2;
- (_Bool)runIfLastTimeWasAtLeast:(double)arg1 identifier:(id)arg2 persistent:(_Bool)arg3 block:(CDUnknownBlockType)arg4;
- (void)resetLastRunTime:(id)arg1;
- (void)runWithIdentifier:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)dispatchMain:(CDUnknownBlockType)arg1;
- (void)dispatchBackground:(CDUnknownBlockType)arg1;
- (void)dispatchMainOrBackground:(_Bool)arg1 block:(CDUnknownBlockType)arg2;
- (void)dispatchDelayed:(CDUnknownBlockType)arg1;
- (void)dispatchMainAfter:(double)arg1 block:(CDUnknownBlockType)arg2;
- (void)dispatchAfter:(double)arg1 block:(CDUnknownBlockType)arg2;
- (void)executeBenchmark:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)dispatchCancelPrevious:(id)arg1 block:(CDUnknownBlockType)arg2;
@end

