//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPropertyListSerialization.h"

@interface NSPropertyListSerialization (PTHNSPropertyListSerializationCategory)
+ (id)propertyListWithPath:(id)arg1 options:(unsigned long long)arg2 format:(unsigned long long *)arg3 error:(out id *)arg4;
+ (_Bool)writePropertyList:(id)arg1 toPath:(id)arg2 format:(unsigned long long)arg3 options:(unsigned long long)arg4 error:(out id *)arg5;
@end

