//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PTHBlurBackgroundTransitioningController.h"

@class NSMutableArray, NSString, PTHBlurBackgroundTransitioningDelegate, PTHBlurBackgroundView, UIView;

@interface PTHAlertView : UIViewController <PTHBlurBackgroundTransitioningController>
{
    NSMutableArray *_contentPositionConstraints;
    PTHBlurBackgroundTransitioningDelegate *_transitioningDelegate;
    UIView *_topView;
    _Bool _progressIndicator;
    NSString *_message;
    NSString *_okButtonTitle;
    CDUnknownBlockType _okBlock;
    NSString *_cancelButtonTitle;
    CDUnknownBlockType _cancelBlock;
    NSString *_otherButtonTitle;
    CDUnknownBlockType _otherBlock;
    CDUnknownBlockType _didDismissBlock;
    long long _returnCode;
    UIView *_contentView;
    UIView *_replaceContentView;
}

+ (id)currentAlertView;
@property(retain, nonatomic) UIView *replaceContentView; // @synthesize replaceContentView=_replaceContentView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) long long returnCode; // @synthesize returnCode=_returnCode;
@property(nonatomic, getter=hasProgressIndicator) _Bool progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(copy, nonatomic) CDUnknownBlockType didDismissBlock; // @synthesize didDismissBlock=_didDismissBlock;
@property(copy, nonatomic) CDUnknownBlockType otherBlock; // @synthesize otherBlock=_otherBlock;
@property(copy, nonatomic) NSString *otherButtonTitle; // @synthesize otherButtonTitle=_otherButtonTitle;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) NSString *cancelButtonTitle; // @synthesize cancelButtonTitle=_cancelButtonTitle;
@property(copy, nonatomic) CDUnknownBlockType okBlock; // @synthesize okBlock=_okBlock;
@property(copy, nonatomic, setter=setOKButtonTitle:) NSString *okButtonTitle; // @synthesize okButtonTitle=_okButtonTitle;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dismissTransition:(id)arg1;
- (void)dismissReplaceTransition:(id)arg1;
- (void)dismissCancelTransition:(id)arg1;
- (void)dismissNormalTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)presentReplaceTransition:(id)arg1;
- (void)presentNormalTransition:(id)arg1;
- (void)_fixHeightIfNeeded;
@property(retain, nonatomic) PTHBlurBackgroundView *backgroundView;
- (void)other:(id)arg1;
- (void)ok:(id)arg1;
- (void)cancel:(id)arg1;
- (void)enablePositionConstraints;
- (void)disablePositionConstraints;
- (void)show:(CDUnknownBlockType)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

