//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHBlurBackgroundTransitioningController.h"
#import "UIDynamicAnimatorDelegate.h"

@class NSMutableArray, PTHActionSheetButton, PTHBlurBackgroundTransitioningDelegate, PTHProgressView, UIDynamicAnimator, UILabel, UIView;

@interface PTHActionSheet : PTHViewController <PTHBlurBackgroundTransitioningController, UIDynamicAnimatorDelegate>
{
    NSMutableArray *_actionButtons;
    UIView *_contentView;
    UIView *_titleBackgroundView;
    UILabel *_titleLabel;
    UIView *_buttonsContainer;
    UIView *_cancelContainer;
    NSMutableArray *_containerConstraints;
    PTHProgressView *_progressView;
    NSMutableArray *_progressViewConstraints;
    _Bool _phoneMode;
    _Bool _scroll;
    _Bool _dismissed;
    UIDynamicAnimator *_animator;
    PTHBlurBackgroundTransitioningDelegate *_transitioningDelegate;
    _Bool _progressIndicator;
    CDUnknownBlockType _cancelBlock;
    PTHActionSheetButton *_selectedButton;
}

@property(retain, nonatomic) PTHActionSheetButton *selectedButton; // @synthesize selectedButton=_selectedButton;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(nonatomic, getter=hasProgressIndicator) _Bool progressIndicator; // @synthesize progressIndicator=_progressIndicator;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)showInView:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)showInView:(id)arg1;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned long long)arg3;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned long long)arg3 block:(CDUnknownBlockType)arg4;
- (void)dismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)cancel;
- (void)_stop:(id)arg1;
- (void)_updateProgressIndicator;
- (void)setTitle:(id)arg1;
- (void)_updateTitle;
- (void)replaceButton:(id)arg1 withButton:(id)arg2;
- (id)addDeleteButton:(id)arg1 selectBlock:(CDUnknownBlockType)arg2;
- (id)addActionButton:(id)arg1 selectBlock:(CDUnknownBlockType)arg2;
- (id)addActionButton:(id)arg1 withCode:(long long)arg2 andButtonType:(long long)arg3;
- (id)addActionButton:(id)arg1 withCode:(long long)arg2 andButtonType:(long long)arg3 selectBlock:(CDUnknownBlockType)arg4;
- (void)loadView;
- (void)loadViewiPad;
- (void)loadViewiPhone;
- (id)newButton:(id)arg1 withCode:(long long)arg2 andButtonType:(long long)arg3;
- (id)newButton:(id)arg1 withCode:(long long)arg2 andButtonType:(long long)arg3 selectBlock:(CDUnknownBlockType)arg4;
- (id)initWithButtonTitles:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

