//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSString;

@interface PTHAnimatedLabel : UILabel
{
    NSString *_labelText;
}

- (void).cxx_destruct;
- (id)text;
- (void)setText:(id)arg1;
- (void)setText:(id)arg1 animated:(_Bool)arg2;

@end

