//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHButton.h"

@class NSString, UIView;

@interface PTHActionSheetButton : PTHButton
{
    long long _actionButtonType;
    NSString *_title;
    long long _code;
    CDUnknownBlockType _selectBlock;
    UIView *_topLineView;
    UIView *_bottomLineView;
}

@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(nonatomic) long long actionButtonType; // @synthesize actionButtonType=_actionButtonType;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
@property(nonatomic) long long code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)stateDidChange;
- (void)configure:(_Bool)arg1 phoneMode:(_Bool)arg2;
- (id)prefix;
- (id)initWithFrame:(struct CGRect)arg1;

@end

