//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSMutableDictionary;

@interface PTHButton : UIButton
{
    NSMutableDictionary *_backgroundColorsDictionary;
    NSMutableDictionary *_backgroundColorNamesDictionary;
    NSMutableDictionary *_tintColorsDictionary;
    NSMutableDictionary *_tintColorNamesDictionary;
    NSMutableDictionary *_titleColorNamesDictionary;
    CDUnknownBlockType _stateChangedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType stateChangedBlock; // @synthesize stateChangedBlock=_stateChangedBlock;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)stateDidChange;
- (void)colorThemeDidChange;
- (void)addTintColorNameForState:(unsigned long long)arg1;
- (void)setTintColorName:(id)arg1 forState:(unsigned long long)arg2;
- (id)tintColorNameForState:(unsigned long long)arg1;
- (void)setTintColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)tintColorForState:(unsigned long long)arg1;
- (void)addBackgroundColorNameForState:(unsigned long long)arg1;
- (void)setBackgroundColorName:(id)arg1 forState:(unsigned long long)arg2;
- (id)backgroundColorNameForState:(unsigned long long)arg1;
- (void)setBackgroundColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)backgroundColorForState:(unsigned long long)arg1;
- (void)setTitleColorName:(id)arg1 forState:(unsigned long long)arg2;
- (id)titleColorNameForState:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

