//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerTransitioningDelegate.h"

@class PTHBlurBackgroundView, UIColor, UIViewController<PTHBlurBackgroundTransitioningController>;

@interface PTHBlurBackgroundTransitioningDelegate : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
{
    UIViewController<PTHBlurBackgroundTransitioningController> *_presentedController;
    double _presentDuration;
    double _dismissDuration;
    unsigned long long _presentAnimationOptions;
    unsigned long long _dismissAnimationOptions;
    double _blurRadius;
    UIColor *_blurTintColor;
    double _blurSaturation;
    PTHBlurBackgroundView *_backgroundView;
    struct CGAffineTransform _backgroundTransform;
}

@property(retain, nonatomic) PTHBlurBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) struct CGAffineTransform backgroundTransform; // @synthesize backgroundTransform=_backgroundTransform;
@property(nonatomic) double blurSaturation; // @synthesize blurSaturation=_blurSaturation;
@property(retain, nonatomic) UIColor *blurTintColor; // @synthesize blurTintColor=_blurTintColor;
@property(nonatomic) double blurRadius; // @synthesize blurRadius=_blurRadius;
@property(nonatomic) unsigned long long dismissAnimationOptions; // @synthesize dismissAnimationOptions=_dismissAnimationOptions;
@property(nonatomic) unsigned long long presentAnimationOptions; // @synthesize presentAnimationOptions=_presentAnimationOptions;
@property(nonatomic) double dismissDuration; // @synthesize dismissDuration=_dismissDuration;
@property(nonatomic) double presentDuration; // @synthesize presentDuration=_presentDuration;
- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animateTransition:(id)arg1;
- (void)dismissTransition:(id)arg1;
- (void)cleanupDismissTransition:(id)arg1;
- (void)executeDismissTransition:(id)arg1;
- (void)prepareDismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)cleanupPresentTransition:(id)arg1;
- (void)executePresentTransition:(id)arg1;
- (void)preparePresentTransition:(id)arg1;
- (id)deviceBlurTintColor;
- (void)addParallaxEffect;
- (double)transitionDuration:(id)arg1;
- (id)initWithPresentedController:(id)arg1;
- (id)init;

@end

