//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableString, UIView;

@interface PTHConstraintCreator : NSObject
{
    NSMutableString *_constraintString;
    NSMutableDictionary *_viewsDictionary;
    UIView *_superview;
    _Bool _vertical;
}

@property(nonatomic) _Bool vertical; // @synthesize vertical=_vertical;
- (void).cxx_destruct;
- (id)constraints;
- (id)constraintsString;
- (void)addPadding:(double)arg1;
- (void)addPadding:(double)arg1 withRelation:(long long)arg2;
- (void)addView:(id)arg1;
- (id)initWithView:(id)arg1;
- (id)init;

@end

