//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIImageView, UISwitch, UIViewController;

@interface PTHColorGroupTableViewCell : UITableViewCell
{
    UIImageView *_disclosureView;
    UIImageView *_checkmarkView;
    UISwitch *_switchView;
    NSString *_colorGroupName;
    _Bool _enabled;
    UIViewController *_viewController;
}

+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (void)initialize;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
- (void).cxx_destruct;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)colorThemeDidChange;
- (void)setAccessoryView:(id)arg1;
@property(readonly, nonatomic) UISwitch *switchView;
@property(readonly, nonatomic) UIImageView *checkmarkView;
@property(readonly, nonatomic) UIImageView *disclosureView;
@property(copy, nonatomic) NSString *detailText;
@property(copy, nonatomic) NSString *text;
- (void)setAccessoryType:(long long)arg1;
- (id)initWithColorGroupName:(id)arg1 reuseIdentifier:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

