//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, UIView;

@interface PTHDial : UIControl
{
    NSArray *_notchViews;
    unsigned long long _value;
    UIView *_backgroundView;
    _Bool _didMove;
}

@property(nonatomic) unsigned long long value; // @synthesize value=_value;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (_Bool)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
@property(copy, nonatomic) NSArray *notchViews;
- (void)setValue:(unsigned long long)arg1 animated:(_Bool)arg2;
- (unsigned long long)_currentValue;
- (long long)_position;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithTitles:(id)arg1;
- (id)initWithTitleArray:(id)arg1;

@end

