//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIDynamicItem.h"

@interface PTHDynamicItemFilter : NSObject <UIDynamicItem>
{
    _Bool _filterVerticalMovement;
    _Bool _filterHorizontalMovement;
    _Bool _freeze;
    id <UIDynamicItem> _item;
    CDUnknownBlockType _filterCenterBlock;
}

@property(nonatomic) _Bool freeze; // @synthesize freeze=_freeze;
@property(nonatomic) _Bool filterHorizontalMovement; // @synthesize filterHorizontalMovement=_filterHorizontalMovement;
@property(nonatomic) _Bool filterVerticalMovement; // @synthesize filterVerticalMovement=_filterVerticalMovement;
@property(copy, nonatomic) CDUnknownBlockType filterCenterBlock; // @synthesize filterCenterBlock=_filterCenterBlock;
@property(readonly, nonatomic) id <UIDynamicItem> item; // @synthesize item=_item;
- (void).cxx_destruct;
@property(nonatomic) struct CGAffineTransform transform;
@property(readonly, nonatomic) struct CGRect bounds;
@property(nonatomic) struct CGPoint center;
- (id)initWithItem:(id)arg1;

@end

