//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface PTHFileCacheDirectory : NSObject
{
    NSString *_cacheDirectory;
    NSMutableDictionary *_cacheDictionary;
    unsigned long long _dirtyCount;
    _Bool _deleted;
    NSString *_fileSuffix;
    double _expirationTimeInterval;
    unsigned long long _maxFileCount;
    unsigned long long _maxDiskSpace;
}

@property(nonatomic, getter=isDeleted) _Bool deleted; // @synthesize deleted=_deleted;
@property(nonatomic) unsigned long long maxDiskSpace; // @synthesize maxDiskSpace=_maxDiskSpace;
@property(nonatomic) unsigned long long maxFileCount; // @synthesize maxFileCount=_maxFileCount;
@property(nonatomic) double expirationTimeInterval; // @synthesize expirationTimeInterval=_expirationTimeInterval;
@property(copy, nonatomic) NSString *fileSuffix; // @synthesize fileSuffix=_fileSuffix;
- (void).cxx_destruct;
- (void)dealloc;
- (void)saveIfNeeded;
- (void)delete;
- (void)removePathWithKey:(id)arg1;
- (void)removeAllPaths;
- (void)addPath:(id)arg1 forKey:(id)arg2;
- (void)addPath:(id)arg1 fileDictionary:(id)arg2 forKey:(id)arg3;
- (id)createPath;
- (id)fileDictionaryForKey:(id)arg1;
- (id)pathForKey:(id)arg1;
- (void)executeInfoForKey:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)_setup;
- (id)initWithCacheDirectory:(id)arg1;

@end

