//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHPageViewDataSource.h"
#import "PTHPageViewDelegate.h"

@class NSMutableArray, PTHHelpStep, PTHHitInsetButton, PTHPageView, PTHPageViewControl, UIView;

@interface PTHHelpController : PTHViewController <PTHPageViewDelegate, PTHPageViewDataSource>
{
    NSMutableArray *_steps;
    PTHHelpStep *_preStep;
    double _descriptionOffset;
    PTHHitInsetButton *_nextButton;
    NSMutableArray *_visibleSteps;
    NSMutableArray *_views;
    UIView *_preView;
    _Bool _delegateRespondsToDidScroll;
    _Bool _firstTime;
    id <PTHHelpControllerDelegate> _delegate;
    Class _pageViewClass;
    PTHPageView *_pageView;
    PTHPageViewControl *_pageViewControl;
}

+ (void)setHasShownFirstTimeHelp:(_Bool)arg1;
+ (_Bool)hasShownFirstTimeHelp;
@property(readonly, nonatomic) PTHPageViewControl *pageViewControl; // @synthesize pageViewControl=_pageViewControl;
@property(readonly, nonatomic) PTHPageView *pageView; // @synthesize pageView=_pageView;
@property(nonatomic) __weak Class pageViewClass; // @synthesize pageViewClass=_pageViewClass;
@property(nonatomic, getter=isFirstTime) _Bool firstTime; // @synthesize firstTime=_firstTime;
@property(nonatomic) __weak id <PTHHelpControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidUnload;
- (void)unload;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(_Bool)arg1;
- (void)pageViewDidEndDecelerating:(id)arg1;
- (void)pageViewDidScroll:(id)arg1;
- (id)pageView:(id)arg1 pageAtIndex:(long long)arg2;
- (id)prependView:(id)arg1;
- (id)_viewForStep:(id)arg1 pageView:(id)arg2;
- (void)next:(id)arg1;
- (unsigned long long)numberOfPagesInPageView:(id)arg1;
- (id)imageViewAtIndex:(long long)arg1;
- (id)actionLabelAtIndex:(long long)arg1;
- (id)descriptionLabelAtIndex:(long long)arg1;
- (id)titleLabelAtIndex:(long long)arg1;
- (id)helpViewAtIndex:(long long)arg1;
- (void)removePreStep;
- (id)newViewWithHelpStep:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

