//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PTHHelpPointerView;

@interface PTHHelpPointer : NSObject
{
    PTHHelpPointerView *_view;
    _Bool _visible;
    CDUnknownBlockType _completion;
}

+ (_Bool)pointerVisible;
- (void).cxx_destruct;
- (void)touch:(id)arg1;
- (void)hide:(_Bool)arg1;
- (void)_hide:(_Bool)arg1 touched:(_Bool)arg2;
- (void)showMessage:(id)arg1 animated:(_Bool)arg2 inView:(id)arg3 pointToView:(id)arg4 direction:(int)arg5 completion:(CDUnknownBlockType)arg6;
- (id)init;

@end

