//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSMutableDictionary, NSMutableOrderedSet, NSNumber, NSObject<OS_dispatch_queue>, NSString, NSTimer, PTHNetworkLoader, _PTHWORMData;

@interface PTHImageLoader : NSObject
{
    NSString *_directoryPath;
    PTHNetworkLoader *_networkLoader;
    NSMutableDictionary *_cacheDictionary;
    NSMutableOrderedSet *_cacheKeySet;
    NSMapTable *_cacheMapTable;
    NSMutableDictionary *_imageDictionaries;
    _PTHWORMData *_currentWORM;
    NSNumber *_currentWORMID;
    _Bool _dirty;
    NSMutableDictionary *_oldWORMs;
    NSObject<OS_dispatch_queue> *_imageLoaderQueue;
    NSTimer *_saveTimer;
    _Bool _debugEnabled;
    unsigned long long _maxDiskSpace;
    unsigned long long _memoryCacheSize;
    unsigned long long _backgroundCacheSize;
}

+ (void)initialize;
@property(nonatomic, getter=isDebugEnabled) _Bool debugEnabled; // @synthesize debugEnabled=_debugEnabled;
@property(nonatomic) unsigned long long backgroundCacheSize; // @synthesize backgroundCacheSize=_backgroundCacheSize;
@property(nonatomic) unsigned long long memoryCacheSize; // @synthesize memoryCacheSize=_memoryCacheSize;
@property(readonly, nonatomic) unsigned long long maxDiskSpace; // @synthesize maxDiskSpace=_maxDiskSpace;
- (void).cxx_destruct;
- (void)dealloc;
- (void)saveIfNeeded;
- (void)_save;
- (void)_clearCacheForBackground;
- (void)_clearCacheForMemory;
- (void)delete;
- (void)storeImagePath:(id)arg1 forURL:(id)arg2 response:(CDUnknownBlockType)arg3;
- (void)loadImagePathFromURL:(id)arg1 fetchIfNeeded:(_Bool)arg2 progress:(CDUnknownBlockType)arg3 response:(CDUnknownBlockType)arg4;
- (void)loadScaledImageFromURL:(id)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4 response:(CDUnknownBlockType)arg5;
- (id)keyForURL:(id)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4;
- (id)keyForURL:(id)arg1;
- (_Bool)setImage:(id)arg1 forKey:(id)arg2;
- (id)newImageForKey:(id)arg1;
- (void)setMaxFileCount:(unsigned long long)arg1;
- (unsigned long long)maxFileCount;
- (void)setExpirationTimeInterval:(double)arg1;
- (double)expirationTimeInterval;
- (void)loadImageFromURL:(id)arg1 response:(CDUnknownBlockType)arg2;
- (id)initWithCacheDirectory:(id)arg1 maxDiskSpace:(unsigned long long)arg2;
- (id)infoPath;

@end

