//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PTHKeyValueObserver : NSObject
{
    id _observer;
    id _object;
    NSString *_keyPath;
    CDUnknownBlockType _changeBlock;
}

@property(copy, nonatomic) CDUnknownBlockType changeBlock; // @synthesize changeBlock=_changeBlock;
@property(readonly, copy, nonatomic) NSString *keyPath; // @synthesize keyPath=_keyPath;
@property(readonly, nonatomic) id object; // @synthesize object=_object;
@property(readonly, nonatomic) id observer; // @synthesize observer=_observer;
- (void).cxx_destruct;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithObject:(id)arg1 forKeyPath:(id)arg2;

@end

