//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class UIColor;

@interface PTHLineTextView : UITextView
{
    double _textHeight;
    UIColor *_lineColor;
}

@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)setFont:(id)arg1;

@end

