//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager;

@interface PTHLocationManager : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_locationManager;
    CDUnknownBlockType _block;
    unsigned long long _locationUpdates;
    double _cachedInterval;
    int _searchType;
    double _desiredAccuracy;
    double _searchTimeout;
    unsigned long long _maxLocationUpdates;
    CLLocation *_location;
}

+ (id)busyError;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) unsigned long long maxLocationUpdates; // @synthesize maxLocationUpdates=_maxLocationUpdates;
@property(nonatomic) double searchTimeout; // @synthesize searchTimeout=_searchTimeout;
@property(nonatomic) double desiredAccuracy; // @synthesize desiredAccuracy=_desiredAccuracy;
@property(nonatomic) int searchType; // @synthesize searchType=_searchType;
- (void).cxx_destruct;
- (void)dealloc;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)_foundBestLocation;
- (void)cancel;
- (void)search:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic, getter=isBusy) _Bool busy;
- (id)init;

@end

