//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>, NSString, NSTimer, PTHFileCacheDirectory;

@interface PTHNetworkLoader : NSObject
{
    PTHFileCacheDirectory *_fileCacheDirectory;
    NSObject<OS_dispatch_queue> *_networkLoaderQueue;
    NSMutableArray *_queuedRequests;
    NSTimer *_dirtyTimer;
    _Bool _debugEnabled;
    _Bool _deleted;
}

@property(nonatomic, getter=isDeleted) _Bool deleted; // @synthesize deleted=_deleted;
@property(nonatomic, getter=isDebugEnabled) _Bool debugEnabled; // @synthesize debugEnabled=_debugEnabled;
- (void).cxx_destruct;
- (void)dealloc;
- (void)saveIfNeeded;
- (void)delete;
- (void)_markDirty;
- (void)_saveDirty;
- (void)deleteFileForNetworkURL:(id)arg1;
- (void)createPathForURL:(id)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadCachedURL:(id)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadNetworkURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadNetworkURL:(id)arg1 queue:(id)arg2 progress:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
@property(copy, nonatomic) NSString *fileSuffix;
@property(nonatomic) unsigned long long maxDiskSpace;
@property(nonatomic) unsigned long long maxFileCount;
@property(nonatomic) double expirationTimeInterval;
- (id)initWithCacheDirectory:(id)arg1;

@end

