//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHBlurBackgroundTransitioningController.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSLayoutConstraint, PTHBlurBackgroundTransitioningDelegate, UIPageControl, UIScrollView, UIView;

@interface PTHNoticeViewController : PTHViewController <PTHBlurBackgroundTransitioningController, UIScrollViewDelegate>
{
    NSArray *_notices;
    PTHBlurBackgroundTransitioningDelegate *_transitioningDelegate;
    UIView *_noticeContainerView;
    NSLayoutConstraint *_noticeContainerBottomConstraint;
    UIScrollView *_noticeScrollView;
    UIPageControl *_noticePageControl;
}

+ (void)initialize;
+ (void)_showNotices;
+ (void)popNoticesDisabled;
+ (void)pushNoticesDisabled;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)close;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_noticePageControlChanged;
- (id)newViewForNotice:(id)arg1;
- (void)loadView;
- (id)initWithNotices:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

