//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableDictionary, PTHPageViewControl, UIScrollView;

@interface PTHPageView : UIView <UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    NSMutableDictionary *_pages;
    long long _currentPage;
    _Bool _vertical;
    unsigned long long _pageCount;
    long long _pageCacheSize;
    _Bool _resizing;
    PTHPageViewControl *_pageViewControl;
    _Bool _delegateRespondsToDidScroll;
    id <PTHPageViewDataSource> _dataSource;
    id <PTHPageViewDelegate> _delegate;
}

@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) long long pageCacheSize; // @synthesize pageCacheSize=_pageCacheSize;
@property(nonatomic) _Bool vertical; // @synthesize vertical=_vertical;
@property(retain, nonatomic) PTHPageViewControl *pageViewControl; // @synthesize pageViewControl=_pageViewControl;
@property(nonatomic) __weak id <PTHPageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <PTHPageViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) struct CGPoint contentOffset;
@property(readonly, nonatomic) double currentPageOffset;
@property(readonly, nonatomic) UIView *currentPageView;
- (void)reloadData;
- (void)updateContentSize;
- (void)_updatePageViews;
- (void)_addPageAtIndex:(long long)arg1;
- (void)_positionViewPage:(id)arg1 atIndex:(long long)arg2;
- (void)setCurrentPage:(long long)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_setup;

@end

