//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSMutableArray, PTHPageView, UIImage;

@interface PTHPageViewControl : UIControl
{
    NSMutableArray *_dotViews;
    long long _currentPage;
    unsigned long long _pageCount;
    UIImage *_pageDotImage;
    UIImage *_pageDotSelectedImage;
    unsigned long long _dotSpacing;
    _Bool _hidesForSinglePage;
    PTHPageView *_pageView;
}

@property(nonatomic) unsigned long long pageCount; // @synthesize pageCount=_pageCount;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) _Bool hidesForSinglePage; // @synthesize hidesForSinglePage=_hidesForSinglePage;
@property(nonatomic) unsigned long long dotSpacing; // @synthesize dotSpacing=_dotSpacing;
@property(retain, nonatomic) UIImage *pageDotSelectedImage; // @synthesize pageDotSelectedImage=_pageDotSelectedImage;
@property(retain, nonatomic) UIImage *pageDotImage; // @synthesize pageDotImage=_pageDotImage;
@property(nonatomic) __weak PTHPageView *pageView; // @synthesize pageView=_pageView;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)switchPageIfNeeded:(id)arg1 event:(id)arg2;
- (void)update;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setup;

@end

