//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableDictionary, UIFont, UIPickerView;

@interface PTHPickerSelectionView : UIView
{
    NSMutableDictionary *_labelDictionary;
    UIPickerView *_pickerView;
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) UIFont *font;
- (void)attachToPickerView:(id)arg1;
- (void)removeLabelForComponent:(long long)arg1;
- (void)addLabel:(id)arg1 forComponent:(long long)arg2;
- (id)labelForComponent:(long long)arg1;
- (void)reloadAllComponents;
- (id)initWithFrame:(struct CGRect)arg1;

@end

