//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIImage;

@interface PTHProgressView : UIView
{
    UIImage *_maskImage;
    _Bool _isIndeterminate;
    _Bool _isSpinning;
    double _progress;
    double _spinnerWidth;
    UIColor *_spinnerBackgroundColor;
    UIColor *_fromColor;
    UIColor *_toColor;
    double _spinnerIndeterminateDuration;
    NSString *_colorGroupName;
}

@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
@property(nonatomic) double spinnerIndeterminateDuration; // @synthesize spinnerIndeterminateDuration=_spinnerIndeterminateDuration;
@property(retain, nonatomic) UIColor *toColor; // @synthesize toColor=_toColor;
@property(retain, nonatomic) UIColor *fromColor; // @synthesize fromColor=_fromColor;
@property(retain, nonatomic) UIColor *spinnerBackgroundColor; // @synthesize spinnerBackgroundColor=_spinnerBackgroundColor;
@property(nonatomic) double spinnerWidth; // @synthesize spinnerWidth=_spinnerWidth;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (void)drawRect:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)_updateState;
- (void)didMoveToWindow;
- (void)_stopSpinning;
- (void)_startSpinning;
- (void)colorThemeDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

