//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHWindow.h"

@class UIView;

@interface PTHRotatableWindow : PTHWindow
{
    UIView *_containerView;
    long long _currentOrientation;
}

+ (struct CGAffineTransform)transformForOrientation:(long long)arg1;
@property(readonly, nonatomic) long long currentOrientation; // @synthesize currentOrientation=_currentOrientation;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_rotationWillChange:(id)arg1;
- (void)_switchOrientation:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

