//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISearchBar.h"

#import "UISearchBarDelegate.h"

@class NSString;

@interface PTHSearchBar : UISearchBar <UISearchBarDelegate>
{
    NSString *_colorGroupName;
    id <UISearchBarDelegate> _realDelegate;
    _Bool _editing;
}

- (void).cxx_destruct;
- (void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(long long)arg2;
- (void)searchBarResultsListButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarBookmarkButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (_Bool)searchBarShouldEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)setPlaceholder:(id)arg1;
- (void)_updateColors;
- (void)setDelegate:(id)arg1;
- (id)initWithColorGroupName:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

