//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHStaticSectionView.h"

@class NSArray;

@interface PTHStaticOptionsSectionView : PTHStaticSectionView
{
    NSArray *_options;
}

@property(readonly, nonatomic) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (void)_selectedCell:(id)arg1;
- (void)setSelectedOptionIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
@property(nonatomic) unsigned long long selectedOptionIndex;
- (id)initWithOptions:(id)arg1 colorGroupName:(id)arg2;

@end

