//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class ACAccountStore, NSArray;

@interface PTHSettingsTapbotsAboutController : PTHViewController
{
    ACAccountStore *_acAccountStore;
    NSArray *_acAccounts;
}

+ (void)requestACAccounts:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (void)showPrivacy:(id)arg1;
- (void)openReviewPage:(id)arg1;
- (void)openGiftPage:(id)arg1;
- (void)follow:(id)arg1 credit:(id)arg2;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

