//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSAttributedString, NSMutableArray, NSString, PTHStaticSectionView, PTHTextField, PTHTextView, UIImage, UIImageView, UILabel, UISlider, UISwitch, UIView;

@interface PTHStaticSectionCell : UIControl
{
    long long _cellType;
    NSString *_colorGroupName;
    NSMutableArray *_subviewConstraints;
    _Bool _hasAttributedText;
    UISwitch *_switchView;
    UIImageView *_checkmarkView;
    UISlider *_sliderView;
    _Bool _checkmarkOn;
    _Bool _disableHorizontalConstraints;
    _Bool _disableVerticalConstraints;
    PTHStaticSectionView *_section;
    UILabel *_textLabel;
    NSAttributedString *_attributeText;
    UIView *_customView;
    PTHTextField *_textField;
    PTHTextView *_textView;
    UIImageView *_imageView;
    UIImageView *_disclosureView;
    UILabel *_detailTextLabel;
    UIView *_separatorConstraintView;
    double _verticalPadding;
    UIView *_leftAccessoryView;
    UIView *_rightAccessoryView;
}

@property(retain, nonatomic) UIView *rightAccessoryView; // @synthesize rightAccessoryView=_rightAccessoryView;
@property(retain, nonatomic) UIView *leftAccessoryView; // @synthesize leftAccessoryView=_leftAccessoryView;
@property(nonatomic) double verticalPadding; // @synthesize verticalPadding=_verticalPadding;
@property(nonatomic) _Bool disableVerticalConstraints; // @synthesize disableVerticalConstraints=_disableVerticalConstraints;
@property(nonatomic) _Bool disableHorizontalConstraints; // @synthesize disableHorizontalConstraints=_disableHorizontalConstraints;
@property(retain, nonatomic) UIView *separatorConstraintView; // @synthesize separatorConstraintView=_separatorConstraintView;
@property(readonly, nonatomic) UISlider *sliderView; // @synthesize sliderView=_sliderView;
@property(readonly, nonatomic) UILabel *detailTextLabel; // @synthesize detailTextLabel=_detailTextLabel;
@property(readonly, nonatomic) UIImageView *disclosureView; // @synthesize disclosureView=_disclosureView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) PTHTextView *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) PTHTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(copy, nonatomic) NSAttributedString *attributeText; // @synthesize attributeText=_attributeText;
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
@property(readonly, nonatomic) long long cellType; // @synthesize cellType=_cellType;
@property(nonatomic) __weak PTHStaticSectionView *section; // @synthesize section=_section;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)colorThemeDidChange;
- (id)colorNamed:(id)arg1;
- (void)_textViewColorUpdate;
- (void)_textFieldColorUpdate;
- (void)_valueChanged;
- (void)setOn:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, getter=isOn) _Bool on;
@property(retain, nonatomic) UIImage *image;
@property(copy, nonatomic) NSString *detailText;
@property(copy, nonatomic) NSString *text;
- (void)updateConstraints;
- (id)initWithType:(long long)arg1;
- (id)initWithType:(long long)arg1 colorGroupName:(id)arg2;

@end

