//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSArray, NSMutableArray, NSMutableSet, NSString, PTHStaticSectionCell, PTHStaticSectionHeaderView, UIView;

@interface PTHStaticSectionView : UIControl
{
    NSMutableArray *_cells;
    NSMutableSet *_hiddenCells;
    UIView *_contentView;
    UIView *_topSeparatorLine;
    NSMutableArray *_separatorLines;
    UIView *_bottomSeparatorLine;
    NSString *_colorGroupName;
    PTHStaticSectionHeaderView *_headerTitleView;
    NSMutableArray *_subviewConstraints;
    _Bool _hideTopSeparator;
    _Bool _hideBottomSeparator;
    UIView *_headerView;
    PTHStaticSectionCell *_selectedCell;
}

+ (void)initialize;
@property(retain, nonatomic) PTHStaticSectionCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(readonly, nonatomic) NSArray *cells; // @synthesize cells=_cells;
@property(nonatomic) _Bool hideBottomSeparator; // @synthesize hideBottomSeparator=_hideBottomSeparator;
@property(nonatomic) _Bool hideTopSeparator; // @synthesize hideTopSeparator=_hideTopSeparator;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(readonly, copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
- (void).cxx_destruct;
- (void)setEnabled:(_Bool)arg1;
- (void)updateConstraints;
- (_Bool)isCellHidden:(id)arg1;
- (void)showCell:(id)arg1;
- (void)hideCell:(id)arg1;
- (void)addCell:(id)arg1;
@property(copy, nonatomic) NSString *headerTitle;
- (id)initWithColorGroupName:(id)arg1;
- (id)_addSeparatorLine;
- (id)initWithFrame:(struct CGRect)arg1;

@end

