//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class CAShapeLayer, NSMutableDictionary, NSString, UIColor;

@interface PTHShapeView : UIControl
{
    struct CGSize _lastSize;
    NSMutableDictionary *_fillColorsDictionary;
    NSMutableDictionary *_fillColorNamesDictionary;
    _Bool _animatePath;
    NSString *_strokeColorName;
    double _cornerRadius;
    long long _shapeType;
    CDUnknownBlockType _shapeBlock;
}

+ (Class)layerClass;
@property(nonatomic) _Bool animatePath; // @synthesize animatePath=_animatePath;
@property(copy, nonatomic) CDUnknownBlockType shapeBlock; // @synthesize shapeBlock=_shapeBlock;
@property(nonatomic) long long shapeType; // @synthesize shapeType=_shapeType;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(copy, nonatomic) NSString *strokeColorName; // @synthesize strokeColorName=_strokeColorName;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)_updateShapePath;
@property(nonatomic) double lineWidth;
@property(retain, nonatomic) UIColor *strokeColor;
- (void)addFillColorNameForState:(unsigned long long)arg1;
- (void)setFillColorName:(id)arg1 forState:(unsigned long long)arg2;
- (id)fillColorNameForState:(unsigned long long)arg1;
- (void)setFillColor:(id)arg1 forState:(unsigned long long)arg2;
- (id)fillColorForState:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *fillColorName;
@property(retain, nonatomic) UIColor *fillColor;
- (void)colorThemeDidChange;
- (void)stateDidChange;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) CAShapeLayer *shapeLayer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

