//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class NSArray, PTHSettingOption, PTHStaticSectionCell, PTHStaticSectionView;

@interface PTHSettingsOptionsViewController : PTHViewController
{
    PTHStaticSectionView *_section;
    NSArray *_options;
    PTHSettingOption *_selectedOption;
    CDUnknownBlockType _valueChangedBlock;
    PTHStaticSectionCell *_selectedCell;
}

@property(retain, nonatomic) PTHStaticSectionCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(copy, nonatomic) CDUnknownBlockType valueChangedBlock; // @synthesize valueChangedBlock=_valueChangedBlock;
@property(retain, nonatomic) PTHSettingOption *selectedOption; // @synthesize selectedOption=_selectedOption;
@property(copy, nonatomic) NSArray *options; // @synthesize options=_options;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)_selectedCell:(id)arg1;
@property(nonatomic) long long selectedValueType;
@property(retain, nonatomic) id selectedValue;
- (void)loadView;

@end

