//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSStreamDelegate.h"

@class NSFileHandle, NSInputStream, NSMutableArray, NSMutableData, NSOutputStream, NSTimer;

@interface PTHStreamHandler : NSObject <NSStreamDelegate>
{
    NSFileHandle *_fileHandle;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    NSMutableData *_inputData;
    _Bool _open;
    NSMutableArray *_outputObjects;
    NSMutableData *_outputBuffer;
    unsigned long long _outputFormat;
    id <PTHStreamHandlerDelegate> _delegate;
    char *_readBuffer;
    _Bool _needsPing;
    NSTimer *_pingTimer;
}

+ (void)initialize;
@property(nonatomic) unsigned long long outputFormat; // @synthesize outputFormat=_outputFormat;
@property(nonatomic) __weak id <PTHStreamHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)close;
- (void)close:(_Bool)arg1;
- (void)ping;
- (_Bool)outputObject:(id)arg1;
- (void)_sendOutput;
- (void)_processInput;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (id)initWithInputStream:(id)arg1 outputStream:(id)arg2;
- (id)initWithFileHandle:(id)arg1;

@end

