//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UISwipeGestureRecognizer.h"

@class UITouch;

@interface PTHSwipePanGestureRecognizer : UISwipeGestureRecognizer
{
    _Bool _began;
    struct CGPoint _beganPoint;
    UITouch *_touch;
    struct CGPoint _point;
    double _timestamp;
    struct CGPoint _lastPoint;
    double _lastTimestamp;
}

- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGPoint)translationInView:(id)arg1;
- (struct CGPoint)velocityInView:(id)arg1;
- (struct CGPoint)locationInView:(id)arg1;
- (void)reset;
- (void)setState:(long long)arg1;

@end

