//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer, NSString;

@interface PTHSoundEffect : NSObject <AVAudioPlayerDelegate>
{
    NSString *_soundFilePath;
    unsigned int _soundID;
    AVAudioPlayer *_player;
}

+ (void)shake;
+ (id)cachedSoundEffectWithCAFFile:(id)arg1;
+ (id)soundEffectWithCAFFile:(id)arg1;
+ (void)setUsesAVPlayer:(_Bool)arg1;
+ (void)setSoundTypesEnabled:(int)arg1;
+ (void)setSoundsEnabled:(_Bool)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stop;
- (void)pause;
- (void)cleanupForBackground;
- (void)cleanup;
- (_Bool)prepareToPlay;
- (_Bool)play;
- (_Bool)play:(int)arg1;
- (id)initWithCAFFile:(id)arg1;
- (id)initWithContentsOfFile:(id)arg1;
- (void)_loadSound;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;

@end

