//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSAttributedString, NSDate, NSDateFormatter, NSFormatter, NSMutableArray, NSMutableDictionary, NSString, NSURL, PTHAttributedLabel, PTHTimeDifferenceFormatter, PTHTweetbotEntity, PTHTweetbotStatus, UIColor, UIImage, UILongPressGestureRecognizer, UIViewController;

@interface PTHTweetbotStatusView : UIView <UIGestureRecognizerDelegate>
{
    PTHTweetbotStatus *_status;
    UIViewController *_viewController;
    long long _interfaceIdiom;
    long long _type;
    PTHAttributedLabel *_attributedLabel;
    UILongPressGestureRecognizer *_longRecognizer;
    NSFormatter *_timeFormatter;
    struct CGRect _profileImageRect;
    struct CGRect _profileBadgeImageRect;
    struct CGRect _selectedShadowRect;
    struct CGRect _textRect;
    struct CGRect _usernameDateRect;
    struct CGRect _separatorLineRect;
    struct CGRect _retweetRect;
    double _retweetTextWidth;
    struct CGRect _mediaRect;
    _Bool _selected;
    _Bool _showsLinks;
    _Bool _ignoresPlaceTouch;
    _Bool _rectsNeedUpdate;
    _Bool _registeredForSecondNotification;
    _Bool _hasMedia;
    PTHTweetbotEntity *_mediaEntity;
    NSMutableDictionary *_mediaImages;
    _Bool _mediaProcessed;
    UIColor *_mediaBackgroundColor;
    long long _mediaSelectedIndex;
    long long _imageType;
    NSMutableArray *_accessibleElements;
    _Bool _animatingFavorited;
    struct CGRect _favoriteRect;
    _Bool _animatingRetweet;
    NSAttributedString *_retweetAttributedString;
    struct CGRect _markedRect;
    PTHTweetbotStatus *_markedStatus;
    _Bool _favorited;
    _Bool _popular;
    _Bool _conversation;
    _Bool _retweeted;
    _Bool _marked;
    _Bool _profileSelected;
    _Bool _retweetSelected;
    _Bool _placeSelected;
    _Bool _showTime;
    _Bool _hideSeparatorLine;
    PTHTweetbotEntity *_selectedEntity;
    NSString *_colorGroupName;
    UIColor *_separatorLineColor;
    UIColor *_timeColor;
    UIColor *_userColor;
    UIColor *_screenNameColor;
    UIColor *_retweetTextColor;
    UIColor *_retweetTextSelectedColor;
    UIColor *_mediaBorderColor;
    UIColor *_mediaSmallShadow;
    UIColor *_avatarOutlineColor;
    UIColor *_backgroundSelectedColor;
    UIColor *_backgroundOverlayPatternColor;
    NSAttributedString *_attributedText;
    UIImage *_profileImage;
    NSURL *_profileImageURL;
    NSString *_username;
    NSString *_screenName;
    NSDate *_date;
    unsigned long long _colorKey;
    UIColor *_topSeparatorLineColor;
}

+ (id)mediaStatusView:(id)arg1;
+ (double)heightForStatus:(id)arg1 imageType:(long long)arg2 forWidth:(double)arg3;
+ (double)heightForStatus:(id)arg1 interfaceIdiom:(long long)arg2 imageType:(long long)arg3 retweet:(_Bool)arg4 forWidth:(double)arg5;
+ (double)heightForStatusText:(id)arg1 forWidth:(double)arg2;
+ (id)attributedTextForStatus:(id)arg1;
+ (id)linkedAttributedTextForAttributedText:(id)arg1 colorGroupName:(id)arg2 isMention:(_Bool)arg3 isSelected:(_Bool)arg4;
+ (id)placeFontForIdiom:(long long)arg1;
+ (id)textFontForIdiom:(long long)arg1;
+ (id)retweetUserFontForIdiom:(long long)arg1;
+ (id)retweetedByFontForIdiom:(long long)arg1;
+ (id)timeFontForIdiom:(long long)arg1;
+ (id)screenNameFontForIdiom:(long long)arg1;
+ (id)userNameFontForIdiom:(long long)arg1;
+ (void)initialize;
@property(retain, nonatomic) UIColor *topSeparatorLineColor; // @synthesize topSeparatorLineColor=_topSeparatorLineColor;
@property(nonatomic) unsigned long long colorKey; // @synthesize colorKey=_colorKey;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(copy, nonatomic) NSString *screenName; // @synthesize screenName=_screenName;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSURL *profileImageURL; // @synthesize profileImageURL=_profileImageURL;
@property(retain, nonatomic) UIImage *profileImage; // @synthesize profileImage=_profileImage;
@property(retain, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) UIColor *backgroundOverlayPatternColor; // @synthesize backgroundOverlayPatternColor=_backgroundOverlayPatternColor;
@property(retain, nonatomic) UIColor *backgroundSelectedColor; // @synthesize backgroundSelectedColor=_backgroundSelectedColor;
@property(retain, nonatomic) UIColor *avatarOutlineColor; // @synthesize avatarOutlineColor=_avatarOutlineColor;
@property(retain, nonatomic) UIColor *mediaSmallShadow; // @synthesize mediaSmallShadow=_mediaSmallShadow;
@property(retain, nonatomic) UIColor *mediaBorderColor; // @synthesize mediaBorderColor=_mediaBorderColor;
@property(retain, nonatomic) UIColor *mediaBackgroundColor; // @synthesize mediaBackgroundColor=_mediaBackgroundColor;
@property(retain, nonatomic) UIColor *retweetTextSelectedColor; // @synthesize retweetTextSelectedColor=_retweetTextSelectedColor;
@property(retain, nonatomic) UIColor *retweetTextColor; // @synthesize retweetTextColor=_retweetTextColor;
@property(retain, nonatomic) UIColor *screenNameColor; // @synthesize screenNameColor=_screenNameColor;
@property(retain, nonatomic) UIColor *userColor; // @synthesize userColor=_userColor;
@property(retain, nonatomic) UIColor *timeColor; // @synthesize timeColor=_timeColor;
@property(nonatomic) _Bool hideSeparatorLine; // @synthesize hideSeparatorLine=_hideSeparatorLine;
@property(readonly, nonatomic) struct CGRect separatorLineRect; // @synthesize separatorLineRect=_separatorLineRect;
@property(retain, nonatomic) UIColor *separatorLineColor; // @synthesize separatorLineColor=_separatorLineColor;
@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
@property(nonatomic) _Bool showTime; // @synthesize showTime=_showTime;
@property(nonatomic) long long imageType; // @synthesize imageType=_imageType;
@property(nonatomic) _Bool ignoresPlaceTouch; // @synthesize ignoresPlaceTouch=_ignoresPlaceTouch;
@property(nonatomic) _Bool placeSelected; // @synthesize placeSelected=_placeSelected;
@property(retain, nonatomic) PTHTweetbotEntity *selectedEntity; // @synthesize selectedEntity=_selectedEntity;
@property(nonatomic, getter=isRetweetSelected) _Bool retweetSelected; // @synthesize retweetSelected=_retweetSelected;
@property(nonatomic, getter=isProfileSelected) _Bool profileSelected; // @synthesize profileSelected=_profileSelected;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic, getter=isMarked) _Bool marked; // @synthesize marked=_marked;
@property(nonatomic, getter=isRetweeted) _Bool retweeted; // @synthesize retweeted=_retweeted;
@property(nonatomic, getter=hasConversation) _Bool conversation; // @synthesize conversation=_conversation;
@property(nonatomic, getter=isPopular) _Bool popular; // @synthesize popular=_popular;
@property(nonatomic, getter=isFavorited) _Bool favorited; // @synthesize favorited=_favorited;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) PTHTweetbotStatus *status; // @synthesize status=_status;
@property(nonatomic) long long interfaceIdiom; // @synthesize interfaceIdiom=_interfaceIdiom;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawRetweetInRect:(struct CGRect)arg1;
- (void)drawFavoriteInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) NSDateFormatter *absoluteDateFormatter;
@property(readonly, nonatomic) PTHTimeDifferenceFormatter *timeDifferenceFormatter;
@property(readonly, copy, nonatomic) NSString *retweetUserString;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_updateRects;
- (struct CGSize)intrinsicContentSize;
- (id)colorNamed:(id)arg1;
- (void)_updateColors;
- (void)_animateRetweet;
- (void)_animateFavorited;
- (void)_updateDateSecond;
- (void)_updateDate;
- (void)_updateProfileImage:(id)arg1;
- (void)_resetDisplayName;
- (void)_resetDisplay;
- (void)colorThemeDidChange;
- (id)initWithFrame:(struct CGRect)arg1;

@end

