//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PTHTweetbotObject, UIViewController;

@interface PTHTweetbotCell : UITableViewCell
{
    UIViewController *_viewController;
    PTHTweetbotObject *_item;
    _Bool _disableReuse;
}

+ (double)selectedDrawerHeightforTableView:(id)arg1;
+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
@property(nonatomic) _Bool disableReuse; // @synthesize disableReuse=_disableReuse;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) PTHTweetbotObject *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)doubleTap;
- (id)reuseIdentifier;
@property(nonatomic, getter=isMarked) _Bool marked;
- (long long)tid;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

