//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSObject<OS_dispatch_queue>;

@interface PTHTweetbotPushController : NSObject
{
    NSMutableArray *_completions;
    NSObject<OS_dispatch_queue> *_networkQueue;
    _Bool _clearBadge;
}

+ (id)sharedController;
+ (id)soundNameFromRemoteDictionary:(id)arg1;
+ (id)alertStringFromRemoteDictionary:(id)arg1;
+ (long long)statusTIDFromRemoteDictionary:(id)arg1;
+ (long long)listTIDFromRemoteDictionary:(id)arg1;
+ (long long)userTIDFromRemoteDictionary:(id)arg1;
+ (long long)directMessageTIDFromRemoteDictionary:(id)arg1;
+ (long long)accountTIDFromRemoteDictionary:(id)arg1;
+ (long long)eventFromRemoteDictionary:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didEnterBackground;
- (void)requestTest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clearBadge:(CDUnknownBlockType)arg1;
- (void)_updateAccountsIfNeeded;
- (void)_updateAccounts;
- (void)__updateAccounts;
- (void)setSettings:(id)arg1 forAccount:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getSettingsForAccount:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_sendRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)requestDeviceDictionary:(CDUnknownBlockType)arg1;
- (void)registerForRemoteNotificationTypes:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)_pushTypeForString:(id)arg1;
- (id)_stringForPushType:(long long)arg1;
- (id)init;
- (void)_setSettings:(id)arg1 forAccount:(id)arg2;

@end

