//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHWindow.h"

@interface PTHTweetbotWindow : PTHWindow
{
}

+ (void)doubleSwipeLeft:(id)arg1;
+ (void)doubleSwipeRight:(id)arg1;
+ (void)doubleSwipeUp:(id)arg1;
+ (void)doubleSwipeDown:(id)arg1;
+ (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
+ (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
+ (id)doubleLeftSwipeRecognizer;
+ (id)doubleRightSwipeRecognizer;
+ (id)doubleUpSwipeRecognizer;
+ (id)doubleDownSwipeRecognizer;
- (void)didAddSubview:(id)arg1;

@end

