//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDate, NSDateFormatter, PTHProgressView, UILabel;

@interface PTHTweetbotRefreshView : UIView
{
    PTHProgressView *_progressView;
    UILabel *_refreshTitleLabel;
    UILabel *_updateDateLabel;
    NSDateFormatter *_updateDateFormatter;
    _Bool _refreshing;
    _Bool _streaming;
    double _progress;
    NSDate *_updateDate;
}

@property(readonly, nonatomic, getter=isStreaming) _Bool streaming; // @synthesize streaming=_streaming;
@property(readonly, nonatomic, getter=isRefreshing) _Bool refreshing; // @synthesize refreshing=_refreshing;
@property(retain, nonatomic) NSDate *updateDate; // @synthesize updateDate=_updateDate;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (void)_updateDate;
- (void)didMoveToWindow:(id)arg1;
- (void)stopStreaming;
- (void)startStreaming;
- (void)stopRefresh;
- (void)startRefresh;
- (void)_updateProgress;
- (id)initWithFrame:(struct CGRect)arg1;

@end

