//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface PTHTweetbotRelationship : NSObject
{
    _Bool _blocked;
    _Bool _followedByCurrentUser;
    _Bool _followsCurrentUser;
    _Bool _canDirectMessage;
    _Bool _showsRetweets;
    NSDate *_updateDate;
}

@property(retain, nonatomic) NSDate *updateDate; // @synthesize updateDate=_updateDate;
@property(nonatomic) _Bool showsRetweets; // @synthesize showsRetweets=_showsRetweets;
@property(nonatomic) _Bool canDirectMessage; // @synthesize canDirectMessage=_canDirectMessage;
@property(nonatomic) _Bool followsCurrentUser; // @synthesize followsCurrentUser=_followsCurrentUser;
@property(nonatomic, getter=isFollowedByCurrentUser) _Bool followedByCurrentUser; // @synthesize followedByCurrentUser=_followedByCurrentUser;
@property(nonatomic, getter=isBlocked) _Bool blocked; // @synthesize blocked=_blocked;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isCurrent;

@end

