//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSLayoutConstraint, NSMutableArray, PTHTweetbotAccount, PTHTweetbotList, UIControl, UILongPressGestureRecognizer, UIScrollView, UIView;

@interface PTHTweetbotHomeTimelineListPickerController : PTHViewController <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
{
    PTHTweetbotAccount *_account;
    UILongPressGestureRecognizer *_listPickerRecognizer;
    UIControl *_contentView;
    UIView *_backgroundView;
    NSLayoutConstraint *_contentTopConstraint;
    UIScrollView *_scrollView;
    NSMutableArray *_listViews;
    PTHTweetbotList *_selectedList;
}

@property(retain, nonatomic) PTHTweetbotList *selectedList; // @synthesize selectedList=_selectedList;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animateTransition:(id)arg1;
- (void)dismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)_updateTopConstraint:(id)arg1;
- (void)_updateTopConstraint;
- (double)transitionDuration:(id)arg1;
- (void)_dismiss;
- (void)_selectedList:(id)arg1;
- (void)gestureRecognizerChanged:(id)arg1;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

