//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class PTHProgressView, PTHTweetbotPostDraft, UIButton, UILabel, UIView, _PTHTweetbotPostGeoPill;

@interface PTHTweetbotPostGeoView : UIControl
{
    id _draftObserver;
    UIButton *_button;
    _PTHTweetbotPostGeoPill *_pill;
    PTHProgressView *_progressView;
    UILabel *_textLabel;
    unsigned long long _state;
    UIControl *_hitView;
    PTHTweetbotPostDraft *_draft;
    id <PTHTweetbotPostViewDelegate> _delegate;
}

@property(readonly, nonatomic) UIView *button; // @synthesize button=_button;
@property(nonatomic) __weak id <PTHTweetbotPostViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)_sendDelegateMessage;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_draftDidUpdate;
- (void)_updateState:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

