//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusView.h"

@interface PTHTweetbotStatusView (PTHTweetbotStatusViewControlCategory)
- (long long)indexOfAccessibilityElement:(id)arg1;
- (id)accessibilityElementAtIndex:(long long)arg1;
- (long long)accessibilityElementCount;
- (id)accessibleElements;
- (_Bool)isAccessibilityElement;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (_Bool)isInCell;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)longPress:(id)arg1;
- (unsigned long long)_touchTypeFromTouch:(struct CGPoint)arg1 getEntity:(id *)arg2 getHitFrame:(struct CGRect *)arg3 getMediaIndex:(long long *)arg4;
- (void)_setupRecognizers;
@end

