//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class CLLocation, NSArray, NSAttributedString, NSMutableArray, NSString, PTHLocationManager, PTHTweetbotAccount, PTHTweetbotError, PTHTweetbotUser;

@interface PTHTweetbotPostDraft : NSObject <NSCoding>
{
    NSMutableArray *_media;
    NSArray *_entities;
    NSArray *_longURLEntities;
    unsigned long long _length;
    PTHLocationManager *_locationManager;
    unsigned long long _postTask;
    double _postProgress;
    _Bool _isEdited;
    _Bool _posting;
    _Bool _deleted;
    NSString *_uuid;
    NSString *_text;
    PTHTweetbotError *_postError;
    PTHTweetbotAccount *_account;
    PTHTweetbotUser *_toUser;
    CLLocation *_location;
    NSString *_placeID;
    NSString *_placeFullName;
    PTHTweetbotError *_lastSearchError;
    long long _replyStatusTID;
    NSString *_replyStatusText;
    NSString *_replyStatusScreenName;
}

@property(readonly, nonatomic) NSArray *media; // @synthesize media=_media;
@property(nonatomic, getter=isDeleted) _Bool deleted; // @synthesize deleted=_deleted;
@property(copy, nonatomic) NSString *replyStatusScreenName; // @synthesize replyStatusScreenName=_replyStatusScreenName;
@property(copy, nonatomic) NSString *replyStatusText; // @synthesize replyStatusText=_replyStatusText;
@property(nonatomic) long long replyStatusTID; // @synthesize replyStatusTID=_replyStatusTID;
@property(readonly, nonatomic) PTHTweetbotError *lastSearchError; // @synthesize lastSearchError=_lastSearchError;
@property(copy, nonatomic) NSString *placeFullName; // @synthesize placeFullName=_placeFullName;
@property(copy, nonatomic) NSString *placeID; // @synthesize placeID=_placeID;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) PTHTweetbotUser *toUser; // @synthesize toUser=_toUser;
@property(nonatomic) __weak PTHTweetbotAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) PTHTweetbotError *postError; // @synthesize postError=_postError;
@property(nonatomic, getter=isPosting) _Bool posting; // @synthesize posting=_posting;
@property(readonly, nonatomic) _Bool isEdited; // @synthesize isEdited=_isEdited;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (void)_uploadMedia:(double)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_shortenURLs:(double)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (void)post:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)canAddMediumType:(long long)arg1;
- (void)deleteMedium:(id)arg1;
- (void)addMedium:(id)arg1;
- (void)delete;
@property(readonly, nonatomic) _Bool isDirectMessage;
- (void)resetLength;
@property(readonly, nonatomic) unsigned long long length;
@property(readonly, nonatomic) NSArray *longURLEntities;
@property(readonly, nonatomic) NSArray *entities;
@property(readonly, nonatomic) NSAttributedString *attributedText;
@property(readonly, nonatomic) NSString *postText;
- (void)appendText:(id)arg1;
- (void)cancelPlaceSearch;
@property(readonly, nonatomic) NSString *locationTitle;
@property(readonly, nonatomic) _Bool isSearching;
- (void)startPlaceSearch;
- (void)setPlace:(id)arg1;
- (void)setReplyStatus:(id)arg1;
- (id)initWithReplyStatus:(id)arg1;
- (id)initWithToUser:(id)arg1;
- (id)initWithAccount:(id)arg1;

@end

