//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class NSArray, NSString, PTHStaticSectionCell, PTHStaticSectionView, PTHTweetbotAccount, UIScrollView;

@interface PTHTweetbotServicesSettingsController : PTHViewController
{
    PTHTweetbotAccount *_account;
    NSArray *_serviceClasses;
    UIScrollView *_scrollView;
    PTHStaticSectionView *_section;
    PTHStaticSectionCell *_showMarkerCell;
    NSString *_currentServiceKey;
    NSString *_descriptionTitle;
    PTHStaticSectionCell *_selectedCell;
}

@property(retain, nonatomic) PTHStaticSectionCell *selectedCell; // @synthesize selectedCell=_selectedCell;
@property(copy, nonatomic) NSString *descriptionTitle; // @synthesize descriptionTitle=_descriptionTitle;
@property(retain, nonatomic) NSString *currentServiceKey; // @synthesize currentServiceKey=_currentServiceKey;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_selectedCell:(id)arg1;
@property(nonatomic) __weak Class currentServiceClass;
- (void)loadView;
- (id)initWithAccount:(id)arg1 serviceClasses:(id)arg2;

@end

