//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSDateFormatter, NSDictionary, NSMapTable, NSMutableArray, NSMutableDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSString, NSTimer, PTHTweetbotAccountSettings, PTHTweetbotCurrentUser, PTHTweetbotStreamingController, PTHTweetbotUserCache;

@interface PTHTweetbotAccount : NSObject <NSCoding>
{
    NSDateFormatter *_dateFormatter;
    NSDateFormatter *_searchDateFormatter;
    NSString *_consumerKey;
    NSString *_consumerSecret;
    NSString *_token;
    NSString *_tokenSecret;
    long long _tid;
    PTHTweetbotCurrentUser *_currentUser;
    NSMapTable *_userMapTable;
    NSMapTable *_statusMapTable;
    NSMutableArray *_savingBlocks;
    NSTimer *_saveTimer;
    NSMutableArray *_postDrafts;
    _Bool _postDraftsDirty;
    _Bool _loggedIn;
    unsigned long long _unauthorizedCount;
    PTHTweetbotUserCache *_userCache;
    PTHTweetbotStreamingController *_streamingController;
    NSObject<OS_dispatch_queue> *_accountQueue;
    PTHTweetbotAccountSettings *_settings;
    NSMutableDictionary *_rateLimits;
    NSMutableArray *_verificationBlocks;
    _Bool _directMessageAccess;
    _Bool _dirty;
    _Bool _saving;
    _Bool _deleted;
    _Bool _userNeedsReset;
    _Bool _invalidCredentials;
    NSString *_username;
}

+ (void)verifyCredentials:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)updateServerTimeOffset:(CDUnknownBlockType)arg1;
+ (void)_setServerTimeOffset:(id)arg1;
+ (id)serverDateFormatter;
+ (void)createAccessRequest:(id)arg1 mode:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)createTokenRequest:(id)arg1 mode:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)initialize;
+ (void)moveAccountAtIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
+ (void)removeAccount:(id)arg1;
+ (void)insertAccount:(id)arg1 atIndex:(unsigned long long)arg2;
+ (id)accountWithUsername:(id)arg1;
+ (id)accountWithTID:(long long)arg1;
+ (id)accounts;
+ (void)setAuthHandler:(CDUnknownBlockType)arg1;
+ (void)willTerminate;
+ (id)_accounts;
+ (void)_migrateIfNeeded;
+ (void)_saveAccountTIDs;
+ (id)accountDirectoryForTIDValue:(id)arg1;
@property(nonatomic) _Bool invalidCredentials; // @synthesize invalidCredentials=_invalidCredentials;
@property(nonatomic) _Bool userNeedsReset; // @synthesize userNeedsReset=_userNeedsReset;
@property(nonatomic, getter=isDeleted) _Bool deleted; // @synthesize deleted=_deleted;
@property(nonatomic, getter=isSaving) _Bool saving; // @synthesize saving=_saving;
@property(nonatomic, getter=isDirty) _Bool dirty; // @synthesize dirty=_dirty;
@property(nonatomic, getter=hasDirectMessageAccess) _Bool directMessageAccess; // @synthesize directMessageAccess=_directMessageAccess;
@property(retain, nonatomic) PTHTweetbotCurrentUser *currentUser; // @synthesize currentUser=_currentUser;
@property(nonatomic) long long tid; // @synthesize tid=_tid;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) NSArray *loadedHashtags;
- (void)deletePostDraft:(id)arg1;
- (void)removePostDraft:(id)arg1;
- (void)addPostDraft:(id)arg1;
@property(readonly, nonatomic) NSArray *postDrafts;
- (void)_setPostDraftsDirty;
- (void)deletePostDrafts;
- (void)saveAccountData;
- (void)savePostDrafts;
- (void)_loadPostDrafts;
- (id)_postDraftsPath;
- (id)rateLimitForPath:(id)arg1;
- (void)stopStreaming;
- (void)startStreaming;
@property(readonly, nonatomic) _Bool isStreaming;
- (id)mobilizer;
- (id)movieUploader;
- (id)imageUploader;
- (id)urlShortner;
- (id)bookmarker;
@property(readonly, nonatomic) PTHTweetbotAccountSettings *settings;
- (void)resetCaches;
@property(readonly, copy, nonatomic) NSArray *loadedStatuses;
- (id)statusWithDictionary:(id)arg1;
- (id)statusWithTID:(long long)arg1;
- (void)setStatus:(id)arg1 forTID:(long long)arg2;
- (id)findStatusWithTID:(long long)arg1;
@property(readonly, nonatomic) PTHTweetbotUserCache *userCache;
@property(readonly, copy, nonatomic) NSArray *loadedUsers;
- (id)userWithDictionary:(id)arg1 updatedAt:(id)arg2;
- (id)userWithScreenName:(id)arg1;
- (id)findUserWithScreenName:(id)arg1;
- (id)userWithTID:(long long)arg1;
- (id)findUserWithTID:(long long)arg1;
- (void)setUser:(id)arg1 forTID:(long long)arg2;
- (void)delete;
- (void)saveForTimer:(id)arg1;
- (void)saveForBackground;
- (void)_saveCurrentUser;
- (void)sendRequest:(id)arg1 progress:(CDUnknownBlockType)arg2 handleResponse:(CDUnknownBlockType)arg3;
- (void)sendRequest:(id)arg1 handleResponse:(CDUnknownBlockType)arg2;
- (void)_sendRequest:(id)arg1 progress:(CDUnknownBlockType)arg2 handleResponse:(CDUnknownBlockType)arg3;
- (void)_verifyAccess:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSDateFormatter *searchDateFormatter;
@property(readonly, nonatomic) NSDateFormatter *dateFormatter;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *accountQueue;
- (id)oAuthEchoHeader;
@property(readonly, nonatomic) NSString *accountDirectory;
@property(readonly, copy, nonatomic) NSString *keyValueStorePrefix;
@property(readonly, copy, nonatomic) NSString *keychainAccountName;
@property(readonly, nonatomic) NSNumber *tidValue;
- (id)_currentUserPath;
- (id)initWithTID:(long long)arg1;
- (id)init;
- (id)deleteRequest:(id)arg1;
- (id)postRequest:(id)arg1;
- (id)getRequest:(id)arg1;
- (id)_request:(id)arg1;
- (void)_updateRequestOAuthValues:(id)arg1;
- (void)updateCredentials:(id)arg1 directMessageAccess:(_Bool)arg2;
@property(readonly, copy, nonatomic) NSDictionary *accessDictionary;
- (id)newAccountKeychainItem;
- (void)_readKeychain;

@end

