//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, NSString, PTHProgressView, PTHShapeView, UILabel;

@interface PTHTweetbotTableViewStatusView : UIView
{
    PTHProgressView *_progressView;
    PTHShapeView *_circleView;
    UILabel *_messageLabel;
    NSLayoutConstraint *_centerYConstraint;
    long long _state;
}

@property(nonatomic) long long state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)dealloc;
@property(copy, nonatomic) NSString *nothingFoundTitle;
- (void)_keyboardDidChange:(id)arg1;
- (void)setState:(long long)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

