//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class NSDictionary, PTHStaticSectionCell, PTHTweetbotAccount, UIScrollView;

@interface PTHTweetbotEditAccountController : PTHViewController <UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    PTHTweetbotAccount *_account;
    UIScrollView *_scrollView;
    PTHStaticSectionCell *_avatarCell;
    PTHStaticSectionCell *_nameCell;
    PTHStaticSectionCell *_locationCell;
    PTHStaticSectionCell *_urlCell;
    PTHStaticSectionCell *_userDescriptionCell;
    _Bool _keyboardHidden;
    NSDictionary *_imageInfo;
}

- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)updateAvatar:(id)arg1;
- (void)_showImagePicker:(long long)arg1 avatarCell:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)updateUI;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_updateImage;
- (void)save;
- (void)_hideKeyboard;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

