//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@class CLCircularRegion, NSString;

@interface PTHTweetbotStatusSearchCursor : PTHTweetbotCursor
{
    NSString *_query;
    NSString *_resultType;
    CLCircularRegion *_region;
}

+ (Class)itemClass;
@property(retain, nonatomic) CLCircularRegion *region; // @synthesize region=_region;
@property(readonly, copy, nonatomic) NSString *resultType; // @synthesize resultType=_resultType;
@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (id)itemsArrayFromResponse:(id)arg1;
- (id)requestURLString;
- (id)queryDictionary;
- (_Bool)usesTIDPagination;
- (_Bool)hasReadStatus;
- (id)uniqueID;
- (id)initWithAccount:(id)arg1 query:(id)arg2 resultType:(id)arg3;

@end

