//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, NSURL, PTHTweetbotEntity;

@interface PTHTweetbotMedium : NSObject <NSCoding>
{
    _Bool _macApp;
    _Bool _iOSApp;
    _Bool _requiresAuth;
    PTHTweetbotEntity *_entity;
    NSString *_title;
    NSURL *_webURL;
    long long _type;
    NSURL *_url;
    NSDictionary *_previewURLDictionary;
    Class _parserClass;
}

+ (id)mediumWithEntity:(id)arg1 dictionary:(id)arg2;
@property(nonatomic) Class parserClass; // @synthesize parserClass=_parserClass;
@property(nonatomic) _Bool requiresAuth; // @synthesize requiresAuth=_requiresAuth;
@property(retain, nonatomic) NSDictionary *previewURLDictionary; // @synthesize previewURLDictionary=_previewURLDictionary;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic, getter=isiOSApp) _Bool iOSApp; // @synthesize iOSApp=_iOSApp;
@property(nonatomic, getter=isMacApp) _Bool macApp; // @synthesize macApp=_macApp;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSURL *webURL; // @synthesize webURL=_webURL;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) __weak PTHTweetbotEntity *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)_loadImage:(id)arg1 maxSize:(struct CGSize)arg2 progress:(CDUnknownBlockType)arg3 response:(CDUnknownBlockType)arg4;
- (void)_loadMovie:(id)arg1 response:(CDUnknownBlockType)arg2;
- (void)loadWithMaxSize:(struct CGSize)arg1 progress:(CDUnknownBlockType)arg2 response:(CDUnknownBlockType)arg3;
- (void)loadPreviewImageWithSize:(struct CGSize)arg1 maxScale:(double)arg2 mode:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 response:(CDUnknownBlockType)arg5;
- (void)_loadImagePathWithURL:(id)arg1 progress:(CDUnknownBlockType)arg2 response:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) _Bool isiTunes;
@property(readonly, nonatomic) _Bool isImage;
@property(readonly, nonatomic) _Bool isMovie;
- (void)loadPreviewURLWithSize:(unsigned long long)arg1 response:(CDUnknownBlockType)arg2;
- (void)loadURL:(CDUnknownBlockType)arg1;
- (id)initWithURL:(id)arg1 type:(long long)arg2 title:(id)arg3 webURL:(id)arg4;

@end

