//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIPanGestureRecognizer, UIView, UIViewController;

@protocol PTHTweetbotMediumViewProtocol <NSObject>
@property(readonly, nonatomic) _Bool shouldPan;
@property(readonly, nonatomic) UIPanGestureRecognizer *panGestureRecognizer;
@property(readonly, nonatomic) UIView *flickView;
@property(readonly, nonatomic) UIView *panView;
@property(nonatomic) __weak UIViewController *controller;
- (void)doubleTap;
- (void)didHide;
- (void)willHide;
- (void)didShow;
- (void)willShow;
- (void)dismissTo:(struct CGRect)arg1;
- (void)didPresent;
- (void)present;
- (void)willPresentFrom:(struct CGRect)arg1;
@end

