//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotAvatarDetailCell.h"

@interface PTHTweetbotDirectMessagesPeopleSearchCell : PTHTweetbotAvatarDetailCell
{
}

+ (double)textHeight;
+ (void)initialize;
+ (struct CGSize)avatarSize;
- (void)setItem:(id)arg1;
- (id)user;

@end

