//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableData, NSMutableSet, NSTimer, PTHOAuthURLRequest, PTHTweetbotAccount, PTHTweetbotCurrentUser;

@interface PTHTweetbotStreamingController : NSObject
{
    PTHTweetbotAccount *_account;
    PTHTweetbotCurrentUser *_currentUser;
    _Bool _shutdown;
    PTHOAuthURLRequest *_request;
    NSMutableSet *_friendTIDs;
    double _reconnectTime;
    NSMutableArray *_streamQueue;
    NSTimer *_backgroundStopTimer;
    NSMutableData *_streamingBuffer;
    unsigned long long _backgroundTaskIdentifier;
    _Bool _isStreaming;
}

+ (void)didStartStreamingAccount:(id)arg1;
+ (_Bool)canStartStreamForAccount:(id)arg1;
+ (id)timestampsForAccount:(id)arg1;
+ (void)initialize;
@property(readonly, nonatomic) _Bool isStreaming; // @synthesize isStreaming=_isStreaming;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_restart;
- (void)stop;
- (_Bool)start;
- (void)_handleUnfavorited:(id)arg1 userDictionary:(id)arg2;
- (void)_handleFavorited:(id)arg1 userDictionary:(id)arg2;
- (void)_handleUnblock:(id)arg1;
- (void)_handleBlock:(id)arg1;
- (void)_handleUnfollow:(id)arg1;
- (void)_handleFollow:(id)arg1;
- (void)_handleUnfavorite:(id)arg1;
- (void)_handleFavorite:(id)arg1;
- (void)_handleDelete:(id)arg1;
- (void)_handleStatus:(id)arg1;
- (void)_handleDirectMessage:(id)arg1;
- (void)runOrQueue:(CDUnknownBlockType)arg1;
- (void)_handleFriends:(id)arg1;
- (void)_didEnterBackground;
- (void)_willEnterForeground;
- (void)_cancelForBackground;
- (void)_shutdownBackgroundTask;
- (id)initWithAccount:(id)arg1;

@end

