//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class NSMutableArray, PTHStaticSectionCell, PTHTweetbotAvatarView, PTHTweetbotList, UIImageView, UILabel;

@interface PTHTweetbotListDetailController : PTHViewController
{
    PTHTweetbotList *_list;
    PTHTweetbotAvatarView *_avatarView;
    UILabel *_nameLabel;
    UILabel *_descriptionLabel;
    UIImageView *_lockImageView;
    UILabel *_footnoteLabel;
    NSMutableArray *_textConstraints;
    PTHStaticSectionCell *_listMembersCell;
    PTHStaticSectionCell *_listFollowersCell;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)showProfile:(id)arg1;
- (void)showFollowers:(id)arg1;
- (void)showMembers:(id)arg1;
- (void)_showController:(id)arg1 cell:(id)arg2;
- (void)_update;
- (void)loadView;
- (id)initWithList:(id)arg1;

@end

