//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSString, PTHKeyValueObserver, PTHTweetbotUser, UIColor, UIImage;

@interface PTHTweetbotAvatarView : UIControl
{
    PTHKeyValueObserver *_userObserver;
    PTHTweetbotUser *_user;
    UIImage *_userImage;
    double _avatarInset;
    double _cornerRadius;
    long long _avatarType;
    NSString *_overlayColorName;
    UIColor *_overlayColor;
    NSString *_strokeColorName;
    UIColor *_strokeColor;
    NSString *_fillColorName;
    UIColor *_fillColor;
}

@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(copy, nonatomic) NSString *fillColorName; // @synthesize fillColorName=_fillColorName;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(copy, nonatomic) NSString *strokeColorName; // @synthesize strokeColorName=_strokeColorName;
@property(retain, nonatomic) UIColor *overlayColor; // @synthesize overlayColor=_overlayColor;
@property(copy, nonatomic) NSString *overlayColorName; // @synthesize overlayColorName=_overlayColorName;
@property(nonatomic) long long avatarType; // @synthesize avatarType=_avatarType;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double avatarInset; // @synthesize avatarInset=_avatarInset;
@property(retain, nonatomic) UIImage *userImage; // @synthesize userImage=_userImage;
@property(retain, nonatomic) PTHTweetbotUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)dealloc;
- (id)accessibilityValue;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)colorThemeDidChange;
@property(readonly, nonatomic) long long currentAvatarType;
- (void)_update;
- (id)initWithFrame:(struct CGRect)arg1;

@end

