//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PTHTweetbotMediumViewProtocol.h"

@class PTHProgressView, UIPanGestureRecognizer, UIViewController;

@interface PTHTweetbotMediumLoadingView : UIView <PTHTweetbotMediumViewProtocol>
{
    PTHProgressView *_progressView;
    UIViewController *_controller;
}

@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)doubleTap;
- (void)longPress:(id)arg1 controller:(id)arg2;
- (void)didHide;
- (void)willHide;
- (void)didShow;
- (void)willShow;
- (void)dismissTo:(struct CGRect)arg1;
- (void)didPresent;
- (void)present;
- (void)willPresentFrom:(struct CGRect)arg1;
@property(readonly, nonatomic) _Bool shouldPan;
@property(readonly, nonatomic) UIPanGestureRecognizer *panGestureRecognizer;
@property(readonly, nonatomic) UIView *flickView;
@property(readonly, nonatomic) UIView *panView;
@property(nonatomic) double progress;
- (id)initWithFrame:(struct CGRect)arg1;

@end

