//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotLoadingTableViewController.h"

@class NSMutableArray, PTHTweetbotListsCursor, PTHTweetbotUser, UIBarButtonItem;

@interface PTHTweetbotManageListMembershipsController : PTHTweetbotLoadingTableViewController
{
    PTHTweetbotUser *_user;
    PTHTweetbotListsCursor *_listsCursor;
    NSMutableArray *_addedLists;
    NSMutableArray *_changedLists;
    _Bool _loadedMemberships;
    UIBarButtonItem *_saveBarButtonItem;
}

+ (Class)cellClass;
- (void).cxx_destruct;
- (void)loadDataIfNeeded:(_Bool)arg1;
- (void)save;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)configure:(id)arg1 forItem:(id)arg2;
- (id)initWithTweetbotUser:(id)arg1;

@end

