//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@class NSString, UIColor, UILabel;

@interface PTHTextView : UITextView
{
    struct CGRect _oldBounds;
    double _oldContentHeight;
    double _preferredHeight;
    UILabel *_placeholderLabel;
    UIColor *_placeholderColor;
    NSString *_placeholderColorName;
    double _maxPreferredHeight;
    double _maxNumberOfLines;
}

@property(nonatomic) double maxNumberOfLines; // @synthesize maxNumberOfLines=_maxNumberOfLines;
@property(nonatomic) double maxPreferredHeight; // @synthesize maxPreferredHeight=_maxPreferredHeight;
@property(retain, nonatomic) NSString *placeholderColorName; // @synthesize placeholderColorName=_placeholderColorName;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGRect)lastLineRect;
- (struct CGRect)firstLineRect;
- (struct CGSize)intrinsicContentSize;
- (void)setBounds:(struct CGRect)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (void)_textDidChange;
- (void)scrollRangeToVisible:(struct _NSRange)arg1;
- (void)setText:(id)arg1;
- (void)_updateHeightIfNeeded;
- (double)preferredHeight;
@property(copy, nonatomic) NSString *placeholder;
- (void)setFont:(id)arg1;
- (void)disableContainerInset;
- (void)colorThemeDidChange;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;

@end

