//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UISearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, PTHColorGroupTableViewCell, PTHSearchBar, PTHTweetbotAccount, UITableView, UIView;

@interface PTHTweetbotCurrentUserSearchController : PTHViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UIGestureRecognizerDelegate>
{
    PTHTweetbotAccount *_account;
    UITableView *_tableView;
    NSMutableArray *_savedSearches;
    PTHSearchBar *_searchBar;
    UIView *_searchBarSeparator;
    NSMutableArray *_searchCells;
    PTHColorGroupTableViewCell *_searchTweetsCell;
    PTHColorGroupTableViewCell *_searchUsersCell;
    PTHColorGroupTableViewCell *_searchNearbyCell;
    PTHColorGroupTableViewCell *_userCell;
    UIView *_savedSearchesHeader;
    UIView *_browseHeader;
    NSArray *_browseArray;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)_hideKeyboard;
- (void)_showKeyboard;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)toggleMode;
@property(readonly, nonatomic) NSArray *currentSavedSearches;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)reloadData;
- (id)initWithAccount:(id)arg1;

@end

