//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PTHBlurBackgroundTransitioningController.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSDictionary, NSLayoutConstraint, NSMutableArray, NSString, PTHBlurBackgroundTransitioningDelegate, UIAttachmentBehavior, UIDynamicAnimator, UIImageView, UIScrollView, UITapGestureRecognizer, UIView, UIView<PTHTweetbotMediumViewProtocol>;

@interface PTHTweetbotMediaController : UIViewController <UIGestureRecognizerDelegate, PTHBlurBackgroundTransitioningController, UIScrollViewDelegate>
{
    UIScrollView *_containerView;
    UIImageView *_backgroundView;
    NSArray *_media;
    NSMutableArray *_mediaViews;
    NSString *_oldAudioSessionCategory;
    PTHBlurBackgroundTransitioningDelegate *_transitioningDelegate;
    struct CGPoint _panViewStartCenter;
    struct UIOffset _panViewTouchOffset;
    _Bool _panningAccessoryView;
    _Bool _flicking;
    UIDynamicAnimator *_flickAnimator;
    UIAttachmentBehavior *_flickAttachmentBehavior;
    unsigned long long _selectedMediumIndex;
    NSLayoutConstraint *_accessoryViewBottomConstraint;
    UITapGestureRecognizer *_doubleTapRecognizer;
    _Bool _shouldCrop;
    unsigned long long _launchMediumIndex;
    NSDictionary *_launchMediumResponseDictionary;
    UIView *_accessoryView;
    UIView *_launchView;
    double _maxScale;
    UIView *_contentView;
    struct CGRect _launchRect;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double maxScale; // @synthesize maxScale=_maxScale;
@property(nonatomic) _Bool shouldCrop; // @synthesize shouldCrop=_shouldCrop;
@property(retain, nonatomic) UIView *launchView; // @synthesize launchView=_launchView;
@property(nonatomic) struct CGRect launchRect; // @synthesize launchRect=_launchRect;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(retain, nonatomic) NSDictionary *launchMediumResponseDictionary; // @synthesize launchMediumResponseDictionary=_launchMediumResponseDictionary;
@property(nonatomic) unsigned long long launchMediumIndex; // @synthesize launchMediumIndex=_launchMediumIndex;
- (void).cxx_destruct;
- (void)dealloc;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)prefersStatusBarHidden;
- (_Bool)doubleSwipeDisabled;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (struct CGRect)_animationLaunchRect;
- (void)didPan:(id)arg1;
- (void)didPanAccessoryView:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)didDoubleTap:(id)arg1;
- (void)didTap:(id)arg1;
@property(readonly, nonatomic) UIView<PTHTweetbotMediumViewProtocol> *selectedMediumView;
- (void)loadView;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidStop;
- (void)viewDidLayoutSubviews;
- (id)initWithMedia:(id)arg1;

@end

