//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotAccountController.h"

#import "PTHUIViewColorNameChangeCategory.h"

@class NSArray;

@interface PTHTweetbotAccountController (PTHTweetbotAccountControllerTabCategory) <PTHUIViewColorNameChangeCategory>
- (void)setViewControllers:(id)arg1;
- (long long)tabAtTabBarPoint:(struct CGPoint)arg1;
- (unsigned long long)tabBarItemIndexAtPoint:(struct CGPoint)arg1;
- (struct CGRect)tabBarItemFrameAtIndex:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSArray *hiddenViewControllers;
- (void)colorThemeDidChange;
- (void)viewDidLayoutSubviews;
- (void)setupTab;
- (void)_updateTabBarItems;
- (void)_tabItemReadChanged:(id)arg1;
- (void)_doubleTap:(id)arg1;
@end

