//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PTHTweetbotMediaParser : NSObject
{
}

+ (void)loadHTMLFromMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)loadMediumTypeFromURLMimeType:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)loadPreviewURLDictionaryForMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)loadURLForMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (long long)mediumTypeForURL:(id)arg1;
+ (_Bool)canParse:(id)arg1 parserClass:(Class *)arg2 type:(long long *)arg3;
+ (id)normalizedHostForURL:(id)arg1;
+ (id)parserClasses;
+ (id)parsableHosts;
+ (void)initialize;

@end

