//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class PTHStaticSectionCell;

@interface PTHTweetbotStreamingSettingsController : PTHViewController
{
    PTHStaticSectionCell *_pinToTopCell;
}

- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)changePinToTop:(id)arg1;
- (void)changeStreaming:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

