//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMediaParser.h"

@interface PTHTweetbotRegexMediaParser : PTHTweetbotMediaParser
{
}

+ (void)loadPreviewURLDictionaryForMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)loadURLForMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)_loadUnknownIfNeededForMedium:(id)arg1 item:(id)arg2 response:(CDUnknownBlockType)arg3;
+ (long long)mediumTypeForEntity:(id)arg1;
+ (id)_parserItemForURL:(id)arg1;
+ (id)parsableHosts;
+ (void)initialize;

@end

