//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PTHShapeView;

@interface PTHTweetbotLaunchController : UIViewController
{
    PTHShapeView *_settingsButton;
    CDUnknownBlockType _completion;
}

+ (void)initialize;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredStatusBarStyle;
- (void)_showSettings:(id)arg1;
- (void)finish;
- (void)showSignIn;
- (void)addAccounts:(id)arg1 store:(id)arg2 cleanup:(CDUnknownBlockType)arg3;
- (void)showSelectAccounts:(id)arg1 store:(id)arg2;
- (void)showThankYou;
- (void)_swapConstraints:(id)arg1 toConstraints:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)runLaunchAnimation:(CDUnknownBlockType)arg1;
- (void)prepareLaunchAnimation;
- (void)loadView;

@end

