//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"

@class NSString, NSURL, PTHTweetbotAccount, PTHTweetbotStatus, UIGestureRecognizer, UILongPressGestureRecognizer, UISwipeGestureRecognizer, UIWebView;

@interface PTHTweetbotWebViewController : PTHViewController <UIGestureRecognizerDelegate, UIScrollViewDelegate, UIWebViewDelegate>
{
    PTHTweetbotAccount *_account;
    PTHTweetbotStatus *_status;
    UIWebView *_webView;
    UISwipeGestureRecognizer *_leftSwipeRecognizer;
    UILongPressGestureRecognizer *_longPressRecognizer;
    NSString *_oldAudioSessionCategory;
    UIGestureRecognizer *_oldInteractivePopGestureRecognizer;
    _Bool _hasControls;
    _Bool _disableMobilizer;
    _Bool _loading;
    NSURL *_url;
}

@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(nonatomic) _Bool disableMobilizer; // @synthesize disableMobilizer=_disableMobilizer;
@property(nonatomic) _Bool hasControls; // @synthesize hasControls=_hasControls;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) PTHTweetbotStatus *status; // @synthesize status=_status;
@property(retain, nonatomic) PTHTweetbotAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)dealloc;
- (void)willMoveToParentViewController:(id)arg1;
- (_Bool)doubleSwipeDisabled;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldHideBackBarButtonTitle;
- (_Bool)shouldPop;
- (unsigned long long)supportedInterfaceOrientations;
- (id)modalCancelButtonTitle;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)_updateLoading;
- (void)_update;
- (void)_share:(id)arg1;
- (void)_stopOrRefresh:(id)arg1;
- (void)_longPress:(id)arg1;
- (void)_leftSwipe:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)loadView;
@property(readonly, nonatomic) UIWebView *webView;
- (id)initWithStatus:(id)arg1;
- (id)initWithAccount:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

