//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotDirectMessagesPeopleSearchCell.h"

@class UIImageView;

@interface PTHTweetbotDirectMessagesPeopleFindCell : PTHTweetbotDirectMessagesPeopleSearchCell
{
    UIImageView *_imageView;
}

- (void).cxx_destruct;
- (void)colorThemeDidChange;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

