//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class NSDateFormatter, PTHStaticOptionsSectionView, PTHStaticSectionCell, PTHStaticSectionView, PTHTweetbotAccount;

@interface PTHTweetbotPushSettingsController : PTHViewController
{
    PTHTweetbotAccount *_account;
    PTHStaticOptionsSectionView *_mentionsSection;
    PTHStaticSectionView *_notificationsSection;
    PTHStaticSectionCell *_lastNotificationCell;
    PTHStaticSectionCell *_requestTestCell;
    long long _lastPushTypes;
    _Bool _needsSettings;
    NSDateFormatter *_dateFormatter;
}

- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_testPush:(id)arg1;
- (void)changePushOption;
- (void)_updateDisplay;
- (void)_showMessage:(id)arg1 actionURL:(id)arg2;
- (void)loadView;
- (unsigned long long)_minuteFromDate:(id)arg1;
- (id)_stringFromMinute:(unsigned long long)arg1;
- (id)_dateFromMinute:(unsigned long long)arg1;
- (id)initWithAccount:(id)arg1;

@end

