//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate, NSDictionary, NSRegularExpression, NSString, PTHTweetbotAccount, PTHTweetbotUser;

@interface PTHTweetbotStatusFilter : NSObject <NSCoding>
{
    long long _userTID;
    NSString *_userScreenName;
    NSRegularExpression *_keywordRegularExpression;
    _Bool _muteMentions;
    _Bool _keywordIsRegularExpression;
    PTHTweetbotAccount *_account;
    NSDate *_expirationDate;
    NSString *_keywordString;
    NSString *_hashtagString;
    NSString *_sourceText;
    NSDictionary *_unknownFilterDictionary;
}

@property(readonly, nonatomic) NSDictionary *unknownFilterDictionary; // @synthesize unknownFilterDictionary=_unknownFilterDictionary;
@property(nonatomic) long long userTID; // @synthesize userTID=_userTID;
@property(copy, nonatomic) NSString *sourceText; // @synthesize sourceText=_sourceText;
@property(copy, nonatomic) NSString *hashtagString; // @synthesize hashtagString=_hashtagString;
@property(nonatomic) _Bool keywordIsRegularExpression; // @synthesize keywordIsRegularExpression=_keywordIsRegularExpression;
@property(copy, nonatomic) NSString *keywordString; // @synthesize keywordString=_keywordString;
@property(nonatomic, getter=shouldMuteMentions) _Bool muteMentions; // @synthesize muteMentions=_muteMentions;
@property(retain, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(nonatomic) __weak PTHTweetbotAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isSimilar:(id)arg1;
- (id)urlValue;
- (void)updateFromURL:(id)arg1;
@property(readonly, nonatomic) NSString *expirationDateString;
@property(readonly, nonatomic) NSString *displayString;
@property(nonatomic) __weak PTHTweetbotUser *user;
@property(readonly, nonatomic, getter=isKeywordFilter) _Bool keywordFilter;
@property(readonly, nonatomic, getter=isSourceFilter) _Bool sourceFilter;
@property(readonly, nonatomic, getter=isHashtagFilter) _Bool hashtagFilter;
@property(readonly, nonatomic, getter=isUserFilter) _Bool userFilter;
@property(readonly, nonatomic) _Bool isValid;
- (_Bool)shouldFilterStatus:(id)arg1;
- (id)initWithAccount:(id)arg1;

@end

