//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSLayoutConstraint, NSMutableArray, PTHButton, PTHTweetbotStatus, PTHTweetbotStatusActionDrawerView, PTHTweetbotStatusView, UIPageControl, UIScrollView, UIView;

@interface PTHTweetbotStatusDetailController : UIViewController <UIScrollViewDelegate>
{
    PTHTweetbotStatus *_status;
    NSArray *_conversationStatuses;
    NSArray *_replyStatuses;
    UIScrollView *_scrollView;
    PTHTweetbotStatusView *_statusView;
    UIView *_detailContainerView;
    PTHButton *_detailFavoritesButton;
    PTHButton *_detailRetweetsButton;
    PTHButton *_detailDateButton;
    PTHButton *_detailViaButton;
    PTHTweetbotStatusActionDrawerView *_drawerView;
    UIScrollView *_mediaView;
    UIPageControl *_mediaPageControl;
    NSMutableArray *_loadedMedia;
    NSArray *_mediaViews;
    NSMutableArray *_mediaViewsConstraints;
    _Bool _loadedConversation;
    _Bool _loadedReplies;
    UIView *_topView;
    NSLayoutConstraint *_scrollViewBottomConstraint;
}

- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)swipeLeft:(id)arg1;
- (void)_showClientOptions:(id)arg1;
- (void)_showClient:(id)arg1;
- (void)_showWebPage:(id)arg1;
- (void)_showRetweets:(id)arg1;
- (void)_showFavorites:(id)arg1;
- (void)_share:(id)arg1;
- (void)_statusWasUpdated;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)_loadRepliesIfNeeded;
- (void)_loadConversationIfNeeded;
- (id)_loadDetailContainerView;
- (id)_loadStatusView;
- (void)_updateDetailContainer;
- (id)_loadMediaView;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidStop:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_mediaPageControlChanged;
- (void)_updateMediaView;
- (id)initWithStatus:(id)arg1;

@end

