//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMediaParser.h"

@class NSRegularExpression;

@interface PTHTweetbotDailyMotionMediaParser : PTHTweetbotMediaParser
{
    NSRegularExpression *_expression;
}

+ (void)loadPreviewURLDictionaryForMedium:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (long long)mediumTypeForEntity:(id)arg1;
+ (id)parsableHosts;
- (void).cxx_destruct;

@end

