//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class PTHTweetbotStatus, PTHTweetbotStatusActionDrawerView, PTHTweetbotStatusView, UIImageView, UIView;

@interface PTHTweetbotStatusCell : PTHTweetbotCell
{
    PTHTweetbotStatusView *_statusView;
    PTHTweetbotStatusActionDrawerView *_drawerView;
    unsigned long long _cellType;
    _Bool _swiping;
    UIView *_swipeBackgroundView;
    double _swipePosition;
    UIView *_swipeSeparatorLine;
    UIImageView *_leftSwipeIndicator;
    UIView *_rightSwipeIndicator;
    UIImageView *_rightActionImageView;
    UIImageView *_rightReplyImageView;
    UIView *_rightTopLineView;
    UIView *_rightBottomLineView;
    int _rightSwipeState;
    _Bool _disableLayout;
}

+ (double)selectedDrawerHeightforTableView:(id)arg1;
+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (Class)statusViewClass;
@property(readonly, nonatomic) PTHTweetbotStatusView *statusView; // @synthesize statusView=_statusView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_animateDrawer:(_Bool)arg1;
- (void)layoutSubviews;
@property(nonatomic, getter=isMarked) _Bool marked;
- (void)setItem:(id)arg1;
- (void)_statusWasUpdated:(id)arg1;
- (void)_userWasUpdated:(id)arg1;
- (void)updateStatus;
- (void)didRetweet;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)swipeLeft;
- (void)setViewController:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(readonly, nonatomic) PTHTweetbotStatus *status;
- (void)rightPanSwipe:(id)arg1;
- (void)leftPanSwipe:(id)arg1;

@end

