//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class NSLayoutConstraint, PTHShapeView, UILabel;

@interface PTHTweetbotPostDraftIndicatorView : UIControl
{
    PTHShapeView *_contentView;
    PTHShapeView *_contentOverlayView;
    PTHShapeView *_foldView;
    NSLayoutConstraint *_contentViewLeftConstraint;
    NSLayoutConstraint *_contentViewTopConstraint;
    UILabel *_draftCountLabel;
    id <PTHTweetbotPostViewDelegate> _delegate;
    unsigned long long _draftCount;
}

@property(nonatomic) unsigned long long draftCount; // @synthesize draftCount=_draftCount;
@property(nonatomic) __weak id <PTHTweetbotPostViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)close:(CDUnknownBlockType)arg1;
- (void)open:(CDUnknownBlockType)arg1;
- (void)_showDrafts;
- (id)initWithFrame:(struct CGRect)arg1;

@end

