//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotService.h"

@interface PTHTweetbotMediaService : PTHTweetbotService
{
}

+ (unsigned long long)maxUploadCount;
+ (_Bool)canUploadMovies;
+ (_Bool)canUploadImages;
+ (id)genericServiceFailureTweetbotError;
+ (id)serviceClasses;
- (void)cancel;
- (void)uploadMedium:(id)arg1 withMessage:(id)arg2 progress:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;

@end

