//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHTweetbotPostViewDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class PTHTweetbotAccount, PTHTweetbotPostDraft, PTHTweetbotPostDraftMedium, PTHTweetbotPostPhoneView;

@interface PTHTweetbotPostController : PTHViewController <PTHTweetbotPostViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    PTHTweetbotAccount *_account;
    PTHTweetbotPostDraft *_draft;
    PTHTweetbotPostPhoneView *_postView;
    _Bool _firstTime;
    PTHTweetbotPostDraftMedium *_pickedMedium;
    struct _NSRange _selectedRange;
}

@property(nonatomic) struct _NSRange selectedRange; // @synthesize selectedRange=_selectedRange;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)post:(id)arg1;
- (void)showLocationOptions:(id)arg1;
- (void)toggleLocation:(id)arg1;
- (void)showCameraOptions:(id)arg1;
- (void)_showImagePicker:(long long)arg1 inView:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)showAccounts:(id)arg1;
- (void)showDrafts:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)_updateSelectedEntity;
- (_Bool)disablesAutomaticKeyboardDismissal;
- (void)searchEntity:(id)arg1 control:(id)arg2;
- (void)replaceEntity:(id)arg1 withText:(id)arg2;
- (void)addHashtag:(id)arg1;
- (void)addUser:(id)arg1;
- (void)_addUserOrHashtag:(id)arg1;
- (id)selectedEntity;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)setAccount:(id)arg1;
- (void)selectedMedium:(id)arg1 control:(id)arg2;
- (void)loadView;
- (void)ok:(id)arg1;
- (id)modalCancelButtonTitle;
- (void)_updatePostButton;
- (id)initWithDraft:(id)arg1;

@end

