//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "UITextViewDelegate.h"

@class NSLayoutConstraint, NSString, PTHHitInsetButton, PTHTextView, PTHTweetbotPostDraft, UILabel;

@interface PTHTweetbotDirectMessageTextView : UIControl <UITextViewDelegate>
{
    PTHTextView *_textView;
    NSLayoutConstraint *_textViewHeightConstraint;
    PTHHitInsetButton *_sendButton;
    UILabel *_counterLabel;
    PTHTweetbotPostDraft *_draft;
}

@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)becomeFirstResponder;
- (void)layoutSubviews;
- (void)textViewDidChange:(id)arg1;
@property(copy, nonatomic) NSString *text;
- (void)_send;
- (void)_keyUpNotification:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

