//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITextFieldDelegate.h"

@class PTHStaticSectionCell, PTHTweetbotAccount;

@interface PTHTweetbotServiceCustomSettingsController : PTHViewController <UITextFieldDelegate>
{
    PTHTweetbotAccount *_account;
    Class _serviceClass;
    PTHStaticSectionCell *_endpointCell;
    _Bool _hasSaved;
}

@property(readonly, nonatomic) _Bool hasSaved; // @synthesize hasSaved=_hasSaved;
- (void).cxx_destruct;
- (void)dealloc;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)save:(id)arg1;
- (void)showHelp:(id)arg1;
- (void)loadView;
- (id)initWithAccount:(id)arg1 serviceClass:(Class)arg2;

@end

