//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString, PTHTweetbotAccount, PTHTweetbotRateLimit;

@interface PTHTweetbotCursor : NSObject <NSCoding>
{
    NSMutableArray *_items;
    PTHTweetbotAccount *_account;
    NSMutableArray *_loadNewerBlocks;
    NSMutableArray *_loadGapBlocks;
    NSMutableArray *_loadOlderBlocks;
    _Bool _hasOlder;
    _Bool _streaming;
    _Bool _loadingNewer;
    _Bool _loadingOlder;
    _Bool _loadingGap;
    _Bool _refreshed;
    _Bool _firstTime;
    NSDate *_updateDate;
    long long _gapTID;
    long long _displayTopTID;
    double _displayOffset;
    double _displayOffsetPercentage;
    long long _markedTID;
    long long _syncTID;
    unsigned long long _syncVersion;
    double _syncOffsetPercentage;
    long long _lastReadTID;
    unsigned long long _unreadItemCount;
    NSString *_nextCursor;
    long long _sinceTID;
    NSDate *_lastLoadNewerDate;
}

+ (unsigned long long)itemSaveCount;
+ (Class)itemClass;
@property(retain, nonatomic) NSDate *lastLoadNewerDate; // @synthesize lastLoadNewerDate=_lastLoadNewerDate;
@property(nonatomic) long long sinceTID; // @synthesize sinceTID=_sinceTID;
@property(copy, nonatomic) NSString *nextCursor; // @synthesize nextCursor=_nextCursor;
@property(nonatomic, getter=isFirstTime) _Bool firstTime; // @synthesize firstTime=_firstTime;
@property(nonatomic, getter=hasRefreshed) _Bool refreshed; // @synthesize refreshed=_refreshed;
@property(readonly, nonatomic) unsigned long long unreadItemCount; // @synthesize unreadItemCount=_unreadItemCount;
@property(nonatomic) long long lastReadTID; // @synthesize lastReadTID=_lastReadTID;
@property(nonatomic) double syncOffsetPercentage; // @synthesize syncOffsetPercentage=_syncOffsetPercentage;
@property(nonatomic) unsigned long long syncVersion; // @synthesize syncVersion=_syncVersion;
@property(nonatomic) long long syncTID; // @synthesize syncTID=_syncTID;
@property(nonatomic) long long markedTID; // @synthesize markedTID=_markedTID;
@property(nonatomic) double displayOffsetPercentage; // @synthesize displayOffsetPercentage=_displayOffsetPercentage;
@property(nonatomic) double displayOffset; // @synthesize displayOffset=_displayOffset;
@property(nonatomic) long long displayTopTID; // @synthesize displayTopTID=_displayTopTID;
@property(readonly, nonatomic, getter=isLoadingGap) _Bool loadingGap; // @synthesize loadingGap=_loadingGap;
@property(readonly, nonatomic) long long gapTID; // @synthesize gapTID=_gapTID;
@property(readonly, nonatomic, getter=isLoadingOlder) _Bool loadingOlder; // @synthesize loadingOlder=_loadingOlder;
@property(readonly, nonatomic, getter=isLoadingNewer) _Bool loadingNewer; // @synthesize loadingNewer=_loadingNewer;
@property(retain, nonatomic) NSDate *updateDate; // @synthesize updateDate=_updateDate;
@property(nonatomic, getter=isStreaming) _Bool streaming; // @synthesize streaming=_streaming;
@property(nonatomic) __weak PTHTweetbotAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)reset;
- (void)updateLastReadTIDIfNeeded:(long long)arg1;
- (void)resetUnreadItemCount;
- (unsigned long long)_unreadItemCount;
@property(readonly, nonatomic, getter=isRead) _Bool read;
@property(readonly, nonatomic) _Bool canSync;
@property(readonly, nonatomic) PTHTweetbotRateLimit *rateLimit;
- (void)loadGap:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSMutableDictionary *gapQueryDictionary;
@property(readonly, nonatomic) _Bool hasGap;
- (void)loadAll:(CDUnknownBlockType)arg1;
- (void)_loadAllOlder:(CDUnknownBlockType)arg1;
- (void)loadOlder:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSMutableDictionary *olderQueryDictionary;
@property(readonly, nonatomic) _Bool hasOlder;
- (void)loadNewerIfNeeded:(CDUnknownBlockType)arg1;
- (void)loadNewer:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSMutableDictionary *refreshQueryDictionary;
@property(readonly, nonatomic) double loadNewerInterval;
@property(readonly, nonatomic) _Bool canLoadNewer;
@property(readonly, nonatomic) _Bool shouldLoadNewer;
@property(readonly, nonatomic) double lastLoadNewerInterval;
@property(readonly, nonatomic) _Bool isLoaded;
@property(readonly, nonatomic) _Bool shouldReload;
- (void)sendRequest:(id)arg1 type:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)handleResponse:(id)arg1 type:(int)arg2 block:(CDUnknownBlockType)arg3;
- (id)newItemWithDictionary:(id)arg1;
- (void)processItems:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)requestForString:(id)arg1 dictionary:(id)arg2;
@property(readonly, nonatomic) _Bool hasReadStatus;
@property(readonly, nonatomic) _Bool usesTIDPagination;
@property(readonly, nonatomic) _Bool usesCursorPagination;
@property(readonly, nonatomic) _Bool needsSort;
@property(readonly, nonatomic) NSMutableDictionary *queryDictionary;
@property(readonly, nonatomic) NSString *requestURLString;
- (id)itemsArrayFromResponse:(id)arg1;
- (void)removeItem:(id)arg1;
- (void)addItem:(id)arg1;
- (long long)nextTID:(long long)arg1;
- (_Bool)containsTID:(long long)arg1;
- (long long)indexOfTID:(long long)arg1;
- (id)itemWithTID:(long long)arg1;
@property(readonly, nonatomic) unsigned long long itemCount;
@property(readonly, nonatomic) NSArray *items;
@property(readonly, copy, nonatomic) NSString *uniqueID;
- (id)initWithAccount:(id)arg1;
- (id)init;

@end

