//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusCursorController.h"

#import "UIGestureRecognizerDelegate.h"

@class PTHTweetbotUser;

@interface PTHTweetbotFavoritesController : PTHTweetbotStatusCursorController <UIGestureRecognizerDelegate>
{
    PTHTweetbotUser *_tweetbotUser;
}

- (void).cxx_destruct;
- (id)nothingFoundTitle;
- (id)searchTitle;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)initWithTweetbotUser:(id)arg1;

@end

