//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotOAuthMediaService.h"

@interface PTHTweetbotImglyMediaService : PTHTweetbotOAuthMediaService
{
}

+ (id)title;
+ (_Bool)canUploadMovies;
+ (_Bool)canUploadImages;
- (id)urlStringFromResponseDictionary:(id)arg1;
- (id)uploadPostDictionary;
- (id)uploadMessageKey;
- (id)uploadMediaKey;
- (id)uploadURL;

@end

