//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "PTHTweetbotSearchTableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSString, NSTimer, PTHSearchBar, PTHTweetbotSearchTableViewController, PTHTweetbotTableViewStatusView, UITableView, UIView;

@interface PTHTweetbotTableViewController : PTHViewController <UITableViewDelegate, UITableViewDataSource, PTHTweetbotSearchTableViewDelegate>
{
    UITableView *_tableView;
    NSMutableArray *_items;
    NSMutableArray *_searchItems;
    UIView *_headerContainer;
    PTHTweetbotSearchTableViewController *_searchTableViewController;
    PTHSearchBar *_searchBar;
    PTHTweetbotTableViewStatusView *_statusView;
    CDUnknownBlockType _endScrollingBlock;
    NSTimer *_endScrollingTimer;
    CDUnknownBlockType _endTrackingBlock;
    NSTimer *_endTrackingTimer;
    unsigned long long _trackingCounter;
    _Bool _isSearching;
    _Bool _disableSearch;
}

+ (unsigned long long)canUpdate;
+ (void)popFreezeUpdates;
+ (void)pushFreezeUpdates;
@property(nonatomic) _Bool disableSearch; // @synthesize disableSearch=_disableSearch;
@property(retain, nonatomic) NSArray *searchItems; // @synthesize searchItems=_searchItems;
@property(readonly, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)accessibilityScroll:(long long)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)_runScrollingBlockIfNeeded;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)_scrollViewDidStop:(id)arg1;
- (void)scrollViewDidStop:(id)arg1;
- (void)searchTableViewController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (void)searchTableViewControllerDidEndSearch:(id)arg1;
- (void)searchTableViewControllerWillBeginSearch:(id)arg1;
- (void)_runTrackingBlockIfNeeded;
- (void)searchTableViewController:(id)arg1 reloadData:(id)arg2;
- (_Bool)searchTableViewController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)selectedItem;
- (id)itemAtIndexPath:(id)arg1;
- (void)updateInsets;
- (_Bool)shouldShowHeaderContainer;
- (void)setContentPosition:(double)arg1 completion:(CDUnknownBlockType)arg2;
- (void)runIfNotTracking:(CDUnknownBlockType)arg1;
- (void)viewDidLayoutSubviews;
@property(readonly, nonatomic) _Bool needsCustomSeparators;
- (void)loadView;
@property(readonly, nonatomic) double topLayoutExtraOffset;
@property(readonly, nonatomic) double bottomLayoutLength;
@property(readonly, nonatomic) double topLayoutLength;
@property(readonly, nonatomic) NSString *toolbarTitle;
@property(readonly, nonatomic) NSString *nothingFoundTitle;
@property(readonly, nonatomic) NSString *itemsTitle;
@property(readonly, nonatomic) NSString *itemTitle;
@property(readonly, nonatomic) unsigned long long itemDisplayCount;
@property(readonly, nonatomic) NSString *searchTitle;
- (Class)cellClass;
- (void)reloadData;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

