//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MPMoviePlayerController, UIViewController;

@interface PTHTweetbotMediumMovieView : UIView
{
    MPMoviePlayerController *_moviePlayerController;
    UIViewController *_controller;
}

@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (void)doubleTap;
- (void)longPress:(id)arg1 controller:(id)arg2;
- (void)didHide;
- (void)willHide;
- (void)didShow;
- (void)willShow;
- (void)dismissTo:(struct CGRect)arg1;
- (void)didPresent;
- (void)present;
- (void)willPresentFrom:(struct CGRect)arg1;
- (_Bool)shouldPan;
- (id)panGestureRecognizer;
- (id)flickView;
- (id)panView;
- (id)initWithMedium:(id)arg1 responseDictionary:(id)arg2;

@end

