//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class NSArray, NSLayoutConstraint, PTHTweetbotAvatarView, PTHTweetbotPostDraft, PTHTweetbotPostDraftIndicatorView, PTHTweetbotPostGeoView, PTHTweetbotPostMediaView, PTHTweetbotPostThreadView, PTHTweetbotPostToolbarView, UIScrollView, UITextView, _PTHTweetbotPostPhoneScrollView;

@interface PTHTweetbotPostPhoneView : UIView <UITextViewDelegate>
{
    _PTHTweetbotPostPhoneScrollView *_scrollView;
    NSLayoutConstraint *_textViewMediaDraftRightConstraint;
    NSLayoutConstraint *_textViewHeightConstraint;
    id _draftObserver;
    UIView *_mediaViewContainer;
    PTHTweetbotPostMediaView *_mediaView;
    NSArray *_media;
    PTHTweetbotPostThreadView *_threadView;
    PTHTweetbotPostGeoView *_geoView;
    PTHTweetbotPostDraftIndicatorView *_draftIndicatorView;
    _Bool _draftIndicatorVisible;
    _Bool _canShowDraftIndicator;
    _Bool _keyboardFirstTime;
    struct CGRect _keyboardFrame;
    _Bool _keyboardVisible;
    PTHTweetbotPostDraft *_draft;
    id <PTHTweetbotPostViewDelegate> _delegate;
    UITextView *_textView;
    PTHTweetbotPostToolbarView *_toolbarView;
    PTHTweetbotAvatarView *_avatarView;
}

@property(readonly, nonatomic) PTHTweetbotPostMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(readonly, nonatomic) PTHTweetbotAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(readonly, nonatomic) PTHTweetbotPostToolbarView *toolbarView; // @synthesize toolbarView=_toolbarView;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(readonly, nonatomic) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <PTHTweetbotPostViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)dealloc;
- (void)layoutSubviews;
@property(readonly, nonatomic) double visibleHeight;
- (void)_showAccounts;
- (void)_updateDraftsIndicator;
- (void)showDraftsIndicatorIfNeeded;
- (unsigned long long)draftCount;
- (void)hideDraftsIndicatorIfNeeded;
- (void)keyboardDidChange:(id)arg1;
- (void)_draftDidUpdate;
- (void)textViewDidChange:(id)arg1;
- (_Bool)_updateTextConstraintIfNeeded;
- (void)_updateContentScroll;
- (void)textViewDidChangeSelection:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

