//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, PTHTweetbotAccount, PTHTweetbotRefreshView, PTHTweetbotTableViewStatusView, UITableView;

@interface PTHTweetbotDirectMessageThreadsController : PTHViewController <UITableViewDelegate, UITableViewDataSource>
{
    PTHTweetbotAccount *_account;
    UITableView *_tableView;
    NSMutableArray *_directMessageThreads;
    PTHTweetbotRefreshView *_refreshView;
    PTHTweetbotTableViewStatusView *_statusView;
    _Bool _hasUpdated;
    _Bool _hasPlayedRefreshPull;
}

+ (void)initialize;
@property(readonly, nonatomic) PTHTweetbotAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)selectDirectMessageThreadForUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_streamingTransitioned;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)updateInsets;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLayoutSubviews;
- (void)loadView;
- (void)_setMarkAllRead:(id)arg1;
- (void)update;
- (void)_updateUnreadTab;
- (void)loadNewerIfNeeded;
- (void)loadNewer;
- (void)_loadNewerDidStop;
- (void)_loadNewerDidStart;
- (void)reloadData;
- (id)initWithAccount:(id)arg1;

@end

