//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface PTHTweetbotThemeController : NSObject
{
    NSDate *_nextAutochangeDate;
    unsigned long long _changeCounter;
    _Bool _themeAutoChangeEnabled;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setTheme:(id)arg1 withAnimation:(unsigned long long)arg2;
- (void)pauseAutochange:(double)arg1;
- (void)_changeIfNeeded;
- (void)_didBecomeActive;
- (void)_defaultsDidChange;
- (id)init;

@end

