//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class PTHHitInsetButton, UIImageView, UIView;

@interface PTHTweetbotLoadMoreCell : PTHTweetbotCell
{
    UIView *_containerView;
    PTHHitInsetButton *_loadButton;
    UIImageView *_spinnerView;
    UIView *_leftOverlayView;
    UIView *_rightOverlayView;
    UIImageView *_middleOverlayView;
    _Bool _loading;
    _Bool _gap;
}

@property(nonatomic, getter=isGap) _Bool gap; // @synthesize gap=_gap;
@property(readonly, nonatomic) PTHHitInsetButton *loadButton; // @synthesize loadButton=_loadButton;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

