//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "PTHUIViewColorNameChangeCategory.h"

@class NSString;

@interface PTHTweetbotNavigationController : UINavigationController <PTHUIViewColorNameChangeCategory>
{
    long long _statusBarStyle;
    long long _fontType;
    _Bool _firstTime;
    NSString *_colorGroupName;
}

@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
- (void).cxx_destruct;
- (void)dealloc;
- (id)childViewControllerForStatusBarStyle;
- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredStatusBarStyle;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (void)pushViewController:(id)arg1 pushBlock:(CDUnknownBlockType)arg2;
- (void)_updateNavigationItemFonts:(id)arg1;
- (void)colorThemeDidChange;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

