//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface PTHTweetbotTwitterConfiguration : NSObject
{
    unsigned long long _httpLength;
    unsigned long long _httpsLength;
    NSArray *_nonUsernamePaths;
}

+ (id)sharedConfiguration;
@property(copy, nonatomic) NSArray *nonUsernamePaths; // @synthesize nonUsernamePaths=_nonUsernamePaths;
@property(nonatomic) unsigned long long httpsLength; // @synthesize httpsLength=_httpsLength;
@property(nonatomic) unsigned long long httpLength; // @synthesize httpLength=_httpLength;
- (void).cxx_destruct;
- (void)updateConfigurationIfNeeded;
- (void)updateWithDictionary:(id)arg1;
- (id)init;

@end

