//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotAccount.h"

@interface PTHTweetbotAccount (PTHTweetbotAccountACCategory)
+ (void)requestACAccounts:(CDUnknownBlockType)arg1;
+ (void)addACAccountsIfNeeded:(CDUnknownBlockType)arg1;
+ (void)addACAccount:(id)arg1 store:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)_reverseAuth:(id)arg1 store:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)reauthenticateViaAC:(CDUnknownBlockType)arg1;
@end

