//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursorController.h"

@class PTHTweetbotCursor, PTHTweetbotUser;

@interface PTHTweetbotUserListedController : PTHTweetbotCursorController
{
    PTHTweetbotUser *_user;
    PTHTweetbotCursor *_listMembershipsCursor;
    PTHTweetbotCursor *_listsCursor;
}

- (void).cxx_destruct;
- (void)_update:(id)arg1;
- (double)topLayoutExtraOffset1;
- (id)modalCancelButtonTitle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (unsigned long long)itemDisplayCount;
- (id)nothingFoundTitle;
- (id)itemsTitle;
- (id)itemTitle;
- (id)searchTitle;
- (Class)cellClass;
- (_Bool)shouldHideBackBarButtonTitle;
- (void)viewDidLoad;
- (id)initWithTweetbotUser:(id)arg1;

@end

