//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@interface PTHTweetbotSentDirectMessagesCursor : PTHTweetbotCursor
{
}

+ (unsigned long long)itemSaveCount;
+ (Class)itemClass;
- (id)queryDictionary;
- (double)loadNewerInterval;
- (id)requestURLString;
- (_Bool)usesTIDPagination;
- (_Bool)shouldReload;

@end

