//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@class NSString;

@interface PTHTweetbotUserSearchCursor : PTHTweetbotCursor
{
    NSString *_query;
}

+ (Class)itemClass;
@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (id)queryDictionary;
- (_Bool)needsSort;
- (id)requestURLString;
- (id)uniqueID;
- (id)initWithAccount:(id)arg1 query:(id)arg2;

@end

