//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, PTHHitInsetButton, PTHTweetbotStatus, UIColor, UIViewController;

@interface PTHTweetbotStatusActionDrawerView : UIView
{
    NSArray *_buttons;
    PTHHitInsetButton *_actionButton;
    PTHHitInsetButton *_replyButton;
    PTHHitInsetButton *_retweetButton;
    PTHHitInsetButton *_favoriteButton;
    PTHHitInsetButton *_shareButton;
    UIColor *_favoritedTintColor;
    _Bool _favorited;
    PTHTweetbotStatus *_status;
    UIViewController *_viewController;
}

@property(nonatomic, getter=isFavorited) _Bool favorited; // @synthesize favorited=_favorited;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) PTHTweetbotStatus *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)showActions:(id)arg1;
- (void)_showActionLongOptions:(id)arg1;
- (void)_showFavoriteLongOptions:(id)arg1;
- (void)_showRetweetLongOptions:(id)arg1;
- (void)retweet;
- (void)toggleFavorite;
- (void)_updateFavorite;
- (void)reply:(id)arg1;
- (void)showShare:(id)arg1;
@property(readonly, nonatomic) UIColor *favoritedTintColor;
- (void)colorThemeDidChange1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

