//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotListCursor.h"

@interface PTHTweetbotListStatusesCursor : PTHTweetbotListCursor
{
}

+ (unsigned long long)itemSaveCount;
+ (Class)itemClass;
- (id)queryDictionary;
- (id)requestURLString;
- (_Bool)canSync;
- (_Bool)usesTIDPagination;
- (_Bool)hasReadStatus;
- (id)newItemWithDictionary:(id)arg1;

@end

