//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface PTHTweetbotSettings : NSObject
{
    _Bool _postInBackground;
    _Bool _streamingEnabled;
    _Bool _streamingPinToTopEnabled;
    _Bool _streamingOverWWANEnabled;
    _Bool _openLinksInBrowser;
    _Bool _badgesEnabled;
    _Bool _roundAvatars;
    _Bool _themeAutoChangeEnabled;
    _Bool _importsACAccounts;
    _Bool _shouldOpenNotifications;
    _Bool _searchPOIs;
    long long _soundType;
    long long _dateFormatType;
    long long _rightSwipeType;
    long long _displayNameType;
    long long _statusViewImageType;
    long long _quoteFormatType;
    long long _newTweetsBarType;
    NSString *_defaultBrowserScheme;
    double _fontSize;
    long long _fontType;
    NSString *_theme;
    double _themeChangeThreshold;
}

+ (id)sharedSettings;
@property(nonatomic) _Bool searchPOIs; // @synthesize searchPOIs=_searchPOIs;
@property(nonatomic) _Bool shouldOpenNotifications; // @synthesize shouldOpenNotifications=_shouldOpenNotifications;
@property(nonatomic) _Bool importsACAccounts; // @synthesize importsACAccounts=_importsACAccounts;
@property(nonatomic) double themeChangeThreshold; // @synthesize themeChangeThreshold=_themeChangeThreshold;
@property(nonatomic) _Bool themeAutoChangeEnabled; // @synthesize themeAutoChangeEnabled=_themeAutoChangeEnabled;
@property(retain, nonatomic) NSString *theme; // @synthesize theme=_theme;
@property(nonatomic) long long fontType; // @synthesize fontType=_fontType;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) _Bool roundAvatars; // @synthesize roundAvatars=_roundAvatars;
@property(nonatomic) _Bool badgesEnabled; // @synthesize badgesEnabled=_badgesEnabled;
@property(nonatomic) _Bool openLinksInBrowser; // @synthesize openLinksInBrowser=_openLinksInBrowser;
@property(copy, nonatomic) NSString *defaultBrowserScheme; // @synthesize defaultBrowserScheme=_defaultBrowserScheme;
@property(nonatomic, getter=isStreamingOverWWANEnabled) _Bool streamingOverWWANEnabled; // @synthesize streamingOverWWANEnabled=_streamingOverWWANEnabled;
@property(nonatomic, getter=isStreamingPinToTopEnabled) _Bool streamingPinToTopEnabled; // @synthesize streamingPinToTopEnabled=_streamingPinToTopEnabled;
@property(nonatomic, getter=isStreamingEnabled) _Bool streamingEnabled; // @synthesize streamingEnabled=_streamingEnabled;
@property(nonatomic) long long newTweetsBarType; // @synthesize newTweetsBarType=_newTweetsBarType;
@property(nonatomic) long long quoteFormatType; // @synthesize quoteFormatType=_quoteFormatType;
@property(nonatomic) long long statusViewImageType; // @synthesize statusViewImageType=_statusViewImageType;
@property(nonatomic) long long displayNameType; // @synthesize displayNameType=_displayNameType;
@property(nonatomic) long long rightSwipeType; // @synthesize rightSwipeType=_rightSwipeType;
@property(nonatomic) long long dateFormatType; // @synthesize dateFormatType=_dateFormatType;
@property(nonatomic) _Bool postInBackground; // @synthesize postInBackground=_postInBackground;
@property(nonatomic) long long soundType; // @synthesize soundType=_soundType;
- (void).cxx_destruct;
- (void)setTab:(long long)arg1 enabled:(_Bool)arg2;
- (_Bool)isTabEnabled:(long long)arg1;
@property(copy, nonatomic) NSMutableArray *importedACAccountNames;
- (_Bool)streamingOverWWANEnabled;
- (id)init;

@end

