//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotAvatarDetailCell.h"

@class PTHTweetbotList;

@interface PTHTweetbotListedCell : PTHTweetbotAvatarDetailCell
{
}

+ (double)textHeight;
+ (void)initialize;
- (void)setItem:(id)arg1;
@property(readonly, nonatomic) PTHTweetbotList *list;
- (void)showDetail:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

