//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusView.h"

@class PTHTweetbotEntity;

@interface PTHTweetbotStatusView (PTHTweetbotStatusViewMediaCategory)
+ (struct CGPoint)mediumSmallImageOriginAtMediumIndex:(unsigned long long)arg1 mediaCount:(unsigned long long)arg2;
+ (unsigned long long)mediumIndexInLargeImageAtPoint:(struct CGPoint)arg1 withFrame:(struct CGRect)arg2 mediaCount:(unsigned long long)arg3;
+ (struct CGRect)mediumLargeImageRectForFrame:(struct CGRect)arg1 mediumIndex:(unsigned long long)arg2 mediaCount:(unsigned long long)arg3;
- (void)drawMedia:(struct CGRect)arg1;
- (void)resetMedia;
@property(retain, nonatomic) PTHTweetbotEntity *mediaEntity;
- (void)loadMediaIfNeeded;
- (struct CGRect)mediumImageRectAtMediumIndex:(unsigned long long)arg1;
@property(nonatomic) long long mediaSelectedIndex;
@end

