//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "PTHTweetbotEntityTextLabelDelegate.h"

@class NSLayoutConstraint, NSMutableArray, PTHKeyValueObserver, PTHTweetbotAvatarView, PTHTweetbotDirectMessage, PTHTweetbotDirectMessagesController, PTHTweetbotEntity, PTHTweetbotEntityTextLabel, PTHTweetbotPostDraft, UIImageView, UILabel, _PTHMaskedImageView;

@interface PTHTweetbotDirectMessageCell : UITableViewCell <PTHTweetbotEntityTextLabelDelegate>
{
    _PTHMaskedImageView *_textBackgroundView;
    PTHTweetbotEntityTextLabel *_entityTextLabel;
    PTHTweetbotAvatarView *_avatarView;
    UILabel *_dateLabel;
    _Bool _registeredForSecondNotification;
    _Bool _wasCurrentUser;
    NSMutableArray *_subviewConstraints;
    NSLayoutConstraint *_entityTextLabelWidthConstraint;
    NSLayoutConstraint *_entityTextLabelHeightConstraint;
    PTHKeyValueObserver *_draftObserver;
    long long _directMessageState;
    double _lastTextSizeCellWidth;
    UIImageView *_imageView;
    PTHTweetbotEntity *_mediaEntity;
    PTHTweetbotDirectMessagesController *_viewController;
    PTHTweetbotDirectMessage *_directMessage;
    PTHTweetbotPostDraft *_draft;
}

+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (struct CGSize)textSizeForItem:(id)arg1 forWidth:(double)arg2;
+ (void)initialize;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
@property(retain, nonatomic) PTHTweetbotDirectMessage *directMessage; // @synthesize directMessage=_directMessage;
@property(nonatomic) __weak PTHTweetbotDirectMessagesController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (void)dealloc;
- (void)layoutSubviews;
- (id)accessibilityValue;
- (id)accessibilityLabel;
- (void)longPressMedia:(id)arg1;
- (void)showMedia;
- (void)_updateDraft;
- (void)_updateTextSizeIfNeeded;
- (void)_updateTextSize;
- (void)_updateDate;
- (void)_updateDateSecond;
- (id)absoluteDateFormatter;
- (id)timeDifferenceFormatter;
- (void)entityTextLabel:(id)arg1 didLongPressEntity:(id)arg2 entityFrame:(struct CGRect)arg3;
- (void)entityTextLabel:(id)arg1 didTouchUpEntity:(id)arg2 entityFrame:(struct CGRect)arg3;
- (void)_showPostDraftOptionsFromRect:(struct CGRect)arg1 inView:(id)arg2 permittedArrowDirections:(unsigned long long)arg3 postDraft:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_showUser;
- (void)_updateColors;
- (void)updateConstraints;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

