//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotObject.h"

@class PTHTweetbotUser;

@interface PTHTweetbotStatusFavorite : PTHTweetbotObject
{
    PTHTweetbotUser *_user;
}

@property(retain, nonatomic) PTHTweetbotUser *user; // @synthesize user=_user;
- (void).cxx_destruct;

@end

