//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class PTHTweetbotAccount;

@interface PTHTweetbotDeveloperAccountSettingsController : PTHViewController
{
    PTHTweetbotAccount *_account;
}

- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)updateUI:(id)arg1;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

