//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursorController.h"

@class PTHTweetbotUser;

@interface PTHTweetbotFollowingController : PTHTweetbotCursorController
{
    PTHTweetbotUser *_tweetbotUser;
    _Bool _userSelectMode;
}

@property _Bool userSelectMode; // @synthesize userSelectMode=_userSelectMode;
- (void).cxx_destruct;
- (id)modalCancelButtonTitle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)nothingFoundTitle;
- (id)itemsTitle;
- (id)itemTitle;
- (id)searchTitle;
- (Class)cellClass;
- (void)viewDidLoad;
- (id)initWithTweetbotUser:(id)arg1;

@end

