//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotAccount.h"

@class PTHTweetbotTrendPlace;

@interface PTHTweetbotAccount (PTHTweetbotTrendPlaceCategory)
- (void)loadTrendPlaces:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) PTHTweetbotTrendPlace *selectedTrendPlace;
@end

