//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface PTHTapbotsInfoApp : NSObject
{
    NSString *_name;
    NSURL *_detailURL;
    NSURL *_launchURL;
    unsigned long long _appID;
    NSString *_imagePath;
    NSURL *_iconURL;
}

@property(readonly, nonatomic) NSURL *iconURL; // @synthesize iconURL=_iconURL;
@property(readonly, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
@property(readonly, nonatomic) unsigned long long appID; // @synthesize appID=_appID;
@property(readonly, nonatomic) NSURL *launchURL; // @synthesize launchURL=_launchURL;
@property(readonly, nonatomic) NSURL *detailURL; // @synthesize detailURL=_detailURL;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)loadImage:(CDUnknownBlockType)arg1;
- (id)initWithDictionary:(id)arg1;

@end

