//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHColorGroupTableViewCell.h"

@class PTHHitInsetButton, PTHTweetbotList, UIImageView;

@interface PTHTweetbotUserListCell : PTHColorGroupTableViewCell
{
    UIImageView *_lockView;
    PTHHitInsetButton *_infoButton;
    id _listObserver;
    PTHTweetbotList *_list;
}

@property(retain, nonatomic) PTHTweetbotList *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (void)colorThemeDidChange;
- (void)showDetail:(id)arg1;
- (id)initWithColorGroupName:(id)arg1 reuseIdentifier:(id)arg2;

@end

