//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, PTHProgressView, UILabel;

@interface PTHTweetbotLoadingCell : UITableViewCell
{
    PTHProgressView *_progressView;
    UILabel *_textLabel;
}

+ (id)cellWithText:(id)arg1;
+ (id)reuseIdentifier;
+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (void)initialize;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *text;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (id)initWithText:(id)arg1;

@end

