//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotTableViewController.h"

@class NSMutableArray, PTHTweetbotCursor, PTHTweetbotCursorGapCell, PTHTweetbotCursorLoadingOlderView, PTHTweetbotCursorUnreadItemsView, PTHTweetbotRefreshView;

@interface PTHTweetbotCursorController : PTHTweetbotTableViewController
{
    NSMutableArray *_cursorItems;
    _Bool _hasPositioned;
    PTHTweetbotRefreshView *_refreshView;
    PTHTweetbotCursorGapCell *_gapCell;
    _Bool _manuallyScrolling;
    _Bool _loadNewerOnAppear;
    _Bool _hasPlayedRefreshPull;
    _Bool _manuallyRefreshing;
    _Bool _loadingOlder;
    _Bool _loadingGap;
    NSMutableArray *_transitionBlocks;
    _Bool _transitioning;
    _Bool _showMark;
    PTHTweetbotCursorLoadingOlderView *_loadingOlderView;
    _Bool _unreadItemsShowing;
    PTHTweetbotCursorUnreadItemsView *_unreadItemsView;
    _Bool _hideNewItemsBar;
    _Bool _disableRefresh;
    PTHTweetbotCursor *_tweetbotCursor;
}

+ (void)showTableViewAnimations:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
@property(nonatomic) _Bool manuallyScrolling; // @synthesize manuallyScrolling=_manuallyScrolling;
@property(nonatomic) _Bool disableRefresh; // @synthesize disableRefresh=_disableRefresh;
@property(retain, nonatomic) PTHTweetbotCursor *tweetbotCursor; // @synthesize tweetbotCursor=_tweetbotCursor;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldShowItem:(id)arg1;
- (void)searchTableViewControllerDidEndSearch:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollToTop;
- (void)_didBecomeActive;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_resetLastRead;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidStop:(id)arg1;
- (void)storePosition;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)_streamingTransitioned;
- (void)loadGap;
- (void)loadOlder;
- (void)loadNewerIfNeeded;
- (void)loadNewer;
- (void)_loadNewerDidStop;
- (void)_loadNewerDidStart;
- (void)didUpdate;
- (void)nextTransition;
- (void)runTransition:(CDUnknownBlockType)arg1;
- (void)update;
- (void)_update;
- (id)newItems;
- (_Bool)updateStatusViewIfNeeded:(id)arg1;
- (_Bool)_deleteItemIfNeeded:(id)arg1;
- (_Bool)_addNonFirstItemIfNeeded:(id)arg1;
- (_Bool)_hideSearchIfNeeded:(id)arg1;
- (_Bool)_updateLastIfNeeded:(id)arg1;
- (_Bool)_updateGapIfNeeded:(id)arg1;
- (void)setItems:(id)arg1;
- (double)_positionForDisplayTopTID;
@property(nonatomic) long long selectedTID;
- (unsigned long long)rowForTID:(long long)arg1;
- (void)updateInsets;
- (void)_syncPositionChanged;
- (void)_syncPositionIfNeeded:(_Bool)arg1;
- (void)_markIfNeeded;
- (void)_updateShowMark;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (unsigned long long)itemDisplayCount;
- (void)_updateUnreadItemsView:(_Bool)arg1;
- (double)_unreadItemsPosition;
@property(readonly, nonatomic) long long fullyVisibleTID;
- (void)_fontSizeChanged;
- (id)initWithTweetbotCursor:(id)arg1;

@end

