//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotUserCursor.h"

@interface PTHTweetbotFollowersCursor : PTHTweetbotUserCursor
{
}

+ (Class)itemClass;
- (void)processItems:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)itemsArrayFromResponse:(id)arg1;
- (id)newItemWithDictionary:(id)arg1;
- (id)queryDictionary;
- (id)requestURLString;
- (_Bool)needsSort;
- (_Bool)usesCursorPagination;

@end

