//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@class NSArray;

@interface PTHTweetbotUserLookupCursor : PTHTweetbotCursor
{
    NSArray *_tids;
}

+ (Class)itemClass;
- (void).cxx_destruct;
- (id)requestURLString;
- (id)queryDictionary;
- (id)requestF1orString:(id)arg1 dictionary:(id)arg2;
- (id)initWithAccount:(id)arg1 tids:(id)arg2;

@end

