//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "MFMailComposeViewControllerDelegate.h"

@interface PTHTweetbotSettingsController : PTHViewController <MFMailComposeViewControllerDelegate>
{
}

+ (id)nameForQuoteFormatType:(long long)arg1;
+ (id)nameForRightSwipeType:(long long)arg1;
+ (id)nameForSoundType:(long long)arg1;
+ (void)initialize;
- (void)willMoveToParentViewController:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (id)modalCancelButtonTitle;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showEmailOptions:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)showAccountSettings:(id)arg1;
- (void)changeTimeFormat:(id)arg1;
- (void)changePostInBackground:(id)arg1;
- (void)changeImportACAccounts:(id)arg1;
- (void)showAbout:(id)arg1;
- (void)showBrowserSettings:(id)arg1;
- (void)showRightSwipeSettings:(id)arg1;
- (void)showQuoteFormatSettings:(id)arg1;
- (void)showStreamingSettings:(id)arg1;
- (void)showDisplaySettings:(id)arg1;
- (void)showSoundSettings:(id)arg1;
- (void)_showDeveloperSettings:(id)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

