//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIInputViewAudioFeedback.h"

@class NSLayoutConstraint, PTHTweetbotEntity, PTHTweetbotPostDraft, PTHTweetbotPostToolbarResultsView, UIButton, UILabel;

@interface PTHTweetbotPostToolbarView : UIView <UIInputViewAudioFeedback>
{
    UIView *_controlsView;
    UILabel *_counterLabel;
    UIButton *_cameraButton;
    UILabel *_instructionsLabel;
    PTHTweetbotPostToolbarResultsView *_resultsView;
    NSLayoutConstraint *_resultsHorizontalConstraint;
    id _draftObserver;
    PTHTweetbotPostDraft *_draft;
    id <PTHTweetbotPostViewDelegate> _delegate;
    PTHTweetbotEntity *_selectedEntity;
    unsigned long long _state;
}

@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) PTHTweetbotEntity *selectedEntity; // @synthesize selectedEntity=_selectedEntity;
@property(nonatomic) __weak id <PTHTweetbotPostViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)_draftDidUpdate;
- (void)addHashtag:(id)arg1;
- (void)addUser:(id)arg1;
- (void)showCameraOptions:(id)arg1;
@property(readonly, nonatomic) _Bool enableInputClicksWhenVisible;
- (id)initWithFrame:(struct CGRect)arg1;

@end

