//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

@class PTHTweetbotAccount;

@interface PTHTweetbotAccountSettingsController : PTHViewController
{
    PTHTweetbotAccount *_account;
}

- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (void)_resetCache:(id)arg1;
- (void)_showMobilizers:(id)arg1;
- (void)_showSync:(id)arg1;
- (void)_showBookmarkers:(id)arg1;
- (void)_showURLShortnerServices:(id)arg1;
- (void)_showMovieUploadServices:(id)arg1;
- (void)_showImageUploadServices:(id)arg1;
- (void)_showPushSettings:(id)arg1;
- (void)_showDeveloperSettings:(id)arg1;
- (void)loadView;
- (id)initWithAccount:(id)arg1;

@end

