//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, PTHTweetbotEntity, PTHTweetbotPostDraft, UIScrollView;

@interface PTHTweetbotPostToolbarResultsView : UIView <UIScrollViewDelegate>
{
    NSArray *_loadedHashtags;
    UIScrollView *_scrollView;
    NSArray *_postToolbarItems;
    NSMutableArray *_visibleBlockViews;
    double _visibleBlockPosition;
    NSMutableArray *_queuedViews;
    PTHTweetbotPostDraft *_draft;
    PTHTweetbotEntity *_selectedEntity;
    id <PTHTweetbotPostViewDelegate> _delegate;
    NSArray *_results;
}

@property(copy, nonatomic) NSArray *results; // @synthesize results=_results;
@property(nonatomic) __weak id <PTHTweetbotPostViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PTHTweetbotEntity *selectedEntity; // @synthesize selectedEntity=_selectedEntity;
@property(retain, nonatomic) PTHTweetbotPostDraft *draft; // @synthesize draft=_draft;
- (void).cxx_destruct;
- (void)dealloc;
- (void)layoutSubviews;
- (void)_selectedCell:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_updateVisibleViews;
- (id)_createCellForToolbarItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

