//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusSearchCursor.h"

@class PTHTweetbotPlace;

@interface PTHTweetbotStatusGeoSearchCursor : PTHTweetbotStatusSearchCursor
{
    double _radius;
    PTHTweetbotPlace *_place;
}

@property(retain, nonatomic) PTHTweetbotPlace *place; // @synthesize place=_place;
@property(nonatomic) double radius; // @synthesize radius=_radius;
- (void).cxx_destruct;
- (id)items1ArrayFromResponse:(id)arg1;
- (id)queryDictionary;
- (void)loadNewer:(CDUnknownBlockType)arg1;

@end

