//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class NSLayoutConstraint, PTHProgressView, PTHTweetbotAvatarView, PTHTweetbotEntity, UIControl, UIImageView, UILabel, _PTHTweetbotStatusMediaCellImageView;

@interface PTHTweetbotStatusMediaCell : PTHTweetbotCell
{
    PTHTweetbotEntity *_mediaEntity;
    _PTHTweetbotStatusMediaCellImageView *_statusImageView;
    PTHProgressView *_progressView;
    UIControl *_headerView;
    NSLayoutConstraint *_headerViewTopConstraint;
    PTHTweetbotAvatarView *_avatarView;
    UILabel *_statusLabel;
    UIImageView *_retweetImageView;
    UIImageView *_playImageView;
    _Bool _imageHidden;
}

+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (void)initialize;
@property(readonly, nonatomic) UIControl *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool imageHidden; // @synthesize imageHidden=_imageHidden;
- (void).cxx_destruct;
- (void)setScrollPosition:(double)arg1;
- (void)setItem:(id)arg1;
- (void)showDetail:(id)arg1;
- (void)showImage:(id)arg1;
- (id)status;
- (void)swipeLeft;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

