//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotStatusCursorController.h"

#import "UIGestureRecognizerDelegate.h"

@class PTHTweetbotUser;

@interface PTHTweetbotMentionsController : PTHTweetbotStatusCursorController <UIGestureRecognizerDelegate>
{
    PTHTweetbotUser *_tweetbotUser;
}

- (void).cxx_destruct;
- (void)_playNewItemsSoundIfNeeded;
- (void)_updateUnreadTab;
- (id)nothingFoundTitle;
- (id)searchTitle;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)shouldShowRemoteNotification:(id)arg1;
- (id)initWithTweetbotUser:(id)arg1;

@end

