//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, NSURL;

@interface PTHTapbotsInfoController : NSObject
{
    NSDictionary *_tapbotsDictionary;
    NSMutableArray *_apps;
    NSMutableArray *_faqs;
    NSMutableArray *_credits;
    NSURL *_detailURL;
    NSURL *_reviewURL;
    NSURL *_giftURL;
    unsigned long long _appID;
}

+ (void)loadImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)sharedController;
@property(readonly, nonatomic) unsigned long long appID; // @synthesize appID=_appID;
@property(readonly, nonatomic) NSURL *giftURL; // @synthesize giftURL=_giftURL;
@property(readonly, nonatomic) NSURL *reviewURL; // @synthesize reviewURL=_reviewURL;
@property(readonly, nonatomic) NSURL *detailURL; // @synthesize detailURL=_detailURL;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
@property(readonly, nonatomic) NSString *updatedFilePath;
@property(readonly, copy, nonatomic) NSArray *credits;
@property(readonly, copy, nonatomic) NSArray *faqs;
@property(readonly, copy, nonatomic) NSArray *apps;
- (id)init;
- (void)_loadFromDictionary:(id)arg1;

@end

