//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIDynamicAnimatorDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerTransitioningDelegate.h"

@class NSLayoutConstraint, NSMutableArray, PTHTweetbotAccount, PTHTweetbotAvatarView, UIControl;

@interface PTHTweetbotAccountQuickPickerController : PTHViewController <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning, UIDynamicAnimatorDelegate>
{
    UIControl *_backgroundView;
    NSMutableArray *_avatarViews;
    PTHTweetbotAvatarView *_currentAvatarView;
    UIControl *_cropView;
    NSLayoutConstraint *_cropViewTopConstraint;
    PTHTweetbotAccount *_selectedAccount;
    PTHTweetbotAvatarView *_navbarAvatarView;
}

@property(retain, nonatomic) PTHTweetbotAvatarView *navbarAvatarView; // @synthesize navbarAvatarView=_navbarAvatarView;
@property(retain, nonatomic) PTHTweetbotAccount *selectedAccount; // @synthesize selectedAccount=_selectedAccount;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)animateTransition:(id)arg1;
- (void)dismissTransition:(id)arg1;
- (void)presentTransition:(id)arg1;
- (void)_updateTopConstraint:(id)arg1;
- (void)_updateTopConstraint;
- (double)transitionDuration:(id)arg1;
- (void)gestureRecognizerChanged:(id)arg1;
- (void)_selectAccount:(id)arg1;
- (void)_dismiss;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

