//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotUser.h"

@class NSArray, NSDate, NSMutableArray, NSMutableSet, PTHTweetbotCursor, PTHTweetbotListsCursor;

@interface PTHTweetbotCurrentUser : PTHTweetbotUser
{
    NSMutableArray *_directMessageThreads;
    NSMutableArray *_directMessages;
    NSMutableArray *_directMessageDrafts;
    NSMutableSet *_blockTIDs;
    NSDate *_blockTIDsLastFetchDate;
    _Bool _blockTIDsUpdating;
    NSMutableSet *_retweetBlockTIDs;
    NSDate *_retweetBlockTIDsLastFetchDate;
    _Bool _retweetBlockTIDsUpdating;
    PTHTweetbotCursor *_homeTimelineCursor;
    PTHTweetbotCursor *_sentDirectMessagesCursor;
    PTHTweetbotCursor *_receivedDirectMessagesCursor;
    PTHTweetbotCursor *_mentionsCursor;
    PTHTweetbotListsCursor *_listsCursor;
    PTHTweetbotCursor *_favoritesCursor;
    PTHTweetbotCursor *_retweetsOfMeCursor;
    PTHTweetbotCursor *_savedSearchesCursor;
    _Bool _mentionsDirectMessageThreadsReadStatus;
    unsigned long long _directMessagesUnreadItemCount;
    long long _directMessageOldestTID;
}

@property(readonly, nonatomic) _Bool mentionsDirectMessageThreadsReadStatus; // @synthesize mentionsDirectMessageThreadsReadStatus=_mentionsDirectMessageThreadsReadStatus;
@property(readonly, nonatomic) long long directMessageOldestTID; // @synthesize directMessageOldestTID=_directMessageOldestTID;
@property(readonly, nonatomic) unsigned long long directMessagesUnreadItemCount; // @synthesize directMessagesUnreadItemCount=_directMessagesUnreadItemCount;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setAccount:(id)arg1;
- (void)reset;
- (void)_mentionsDirectMessageThreadsStatusDidUpdate;
- (void)setMentionsDirectMessageThreadsReadStatus:(_Bool)arg1;
- (void)removeStatusesMatchingFilter:(id)arg1;
- (unsigned long long)numberOfExistingStatusesMatchingFilter:(id)arg1;
- (_Bool)isProbablyRetweetBlocked:(id)arg1;
- (void)_updateRetweetBlockTIDsIfNeeded;
- (void)_disabledRetweet:(id)arg1;
- (void)_enabledRetweet:(id)arg1;
- (_Bool)isProbablyBlocked:(id)arg1;
- (void)_updateBlockTIDsIfNeeded;
- (void)_userUnblocked:(id)arg1;
- (void)_userBlocked:(id)arg1;
@property(readonly, nonatomic) PTHTweetbotCursor *savedSearchesCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *retweetsOfMeCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *favoritesCursor;
@property(readonly, nonatomic) PTHTweetbotListsCursor *listsCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *mentionsCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *homeTimelineCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *receivedDirectMessagesCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *sentDirectMessagesCursor;
- (void)removeDirectMessageDraft:(id)arg1;
- (void)addDirectMessageDraft:(id)arg1;
@property(readonly, nonatomic) NSDate *directMessageUpdateDate;
- (void)refreshDirectMessageThreadsIfNeeded:(CDUnknownBlockType)arg1;
- (void)refreshReceivedDirectMessageThreads:(CDUnknownBlockType)arg1;
- (void)refreshDirectMessageThreads:(CDUnknownBlockType)arg1;
- (void)_receivedDirectMessagesUpdated;
- (void)_sentDirectMessagesUpdated;
- (void)_updateDirectMessageThreads;
- (id)directMessageWithTID:(long long)arg1;
- (void)resetUnreadItemCount;
- (unsigned long long)_directMessagesUnreadItemCount;
@property(readonly, nonatomic) NSArray *directMessages;
@property(readonly, nonatomic) NSArray *directMessageThreads;
- (void)setScreenName:(id)arg1;
- (_Bool)isCurrentUser;
- (void)updateProfileImage:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)updateProfileWithName:(id)arg1 urlString:(id)arg2 location:(id)arg3 description:(id)arg4 result:(CDUnknownBlockType)arg5;
- (id)initWithAccount:(id)arg1 tid:(long long)arg2;

@end

