//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHViewController.h"

#import "UIScrollViewDelegate.h"
#import "UITextFieldDelegate.h"

@class PTHStaticSectionCell, PTHTweetbotAccount, PTHTweetbotList, UIScrollView;

@interface PTHTweetbotUserListEditController : PTHViewController <UIScrollViewDelegate, UITextFieldDelegate>
{
    PTHTweetbotList *_list;
    PTHTweetbotAccount *_account;
    UIScrollView *_scrollView;
    PTHStaticSectionCell *_nameCell;
    PTHStaticSectionCell *_listDescriptionCell;
    PTHStaticSectionCell *_privacyCell;
    _Bool _firstTime;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)showFollowers:(id)arg1;
- (void)save;
- (void)updateUI;
- (void)_hideKeyboard;
- (void)loadView;
- (id)initWithList:(id)arg1;
- (id)initWithAccount:(id)arg1;

@end

