//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHAttributedLabel.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, PTHTweetbotEntity, UIColor, UIFont, UILongPressGestureRecognizer;

@interface PTHTweetbotEntityTextLabel : PTHAttributedLabel <UIGestureRecognizerDelegate>
{
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    _Bool _addedTouchUpTarget;
    struct __CTFont *_ctFont;
    struct __CTFont *_linkCTFont;
    struct __CTFont *_hashtagCTFont;
    struct __CTFont *_stockCTFont;
    struct __CTFont *_mentionCTFont;
    struct __CTFont *_placeCTFont;
    _Bool _selectedPlace;
    _Bool _ignoresBackgroundTouch;
    _Bool _ignoresPlaceTouch;
    PTHTweetbotEntity *_selectedEntity;
    UIFont *_textFont;
    UIFont *_linkFont;
    UIColor *_linkColor;
    UIColor *_linkSelectedColor;
    UIFont *_mentionFont;
    UIColor *_mentionColor;
    UIColor *_mentionSelectedColor;
    UIFont *_hashtagFont;
    UIColor *_hashtagColor;
    UIColor *_hashtagSelectedColor;
    UIFont *_stockFont;
    UIColor *_stockColor;
    UIColor *_stockSelectedColor;
    UIFont *_placeFont;
    UIColor *_placeColor;
    UIColor *_placeSelectedColor;
    NSString *_colorGroupName;
    id <PTHTweetbotEntityTextLabelDelegate> _delegate;
}

@property(nonatomic) __weak id <PTHTweetbotEntityTextLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *colorGroupName; // @synthesize colorGroupName=_colorGroupName;
@property(retain, nonatomic) UIColor *placeSelectedColor; // @synthesize placeSelectedColor=_placeSelectedColor;
@property(retain, nonatomic) UIColor *placeColor; // @synthesize placeColor=_placeColor;
@property(retain, nonatomic) UIFont *placeFont; // @synthesize placeFont=_placeFont;
@property(retain, nonatomic) UIColor *stockSelectedColor; // @synthesize stockSelectedColor=_stockSelectedColor;
@property(retain, nonatomic) UIColor *stockColor; // @synthesize stockColor=_stockColor;
@property(retain, nonatomic) UIFont *stockFont; // @synthesize stockFont=_stockFont;
@property(retain, nonatomic) UIColor *hashtagSelectedColor; // @synthesize hashtagSelectedColor=_hashtagSelectedColor;
@property(retain, nonatomic) UIColor *hashtagColor; // @synthesize hashtagColor=_hashtagColor;
@property(retain, nonatomic) UIFont *hashtagFont; // @synthesize hashtagFont=_hashtagFont;
@property(retain, nonatomic) UIColor *mentionSelectedColor; // @synthesize mentionSelectedColor=_mentionSelectedColor;
@property(retain, nonatomic) UIColor *mentionColor; // @synthesize mentionColor=_mentionColor;
@property(retain, nonatomic) UIFont *mentionFont; // @synthesize mentionFont=_mentionFont;
@property(retain, nonatomic) UIColor *linkSelectedColor; // @synthesize linkSelectedColor=_linkSelectedColor;
@property(retain, nonatomic) UIColor *linkColor; // @synthesize linkColor=_linkColor;
@property(retain, nonatomic) UIFont *linkFont; // @synthesize linkFont=_linkFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) _Bool ignoresPlaceTouch; // @synthesize ignoresPlaceTouch=_ignoresPlaceTouch;
@property(nonatomic) _Bool ignoresBackgroundTouch; // @synthesize ignoresBackgroundTouch=_ignoresBackgroundTouch;
@property(nonatomic) _Bool selectedPlace; // @synthesize selectedPlace=_selectedPlace;
@property(retain, nonatomic) PTHTweetbotEntity *selectedEntity; // @synthesize selectedEntity=_selectedEntity;
- (void).cxx_destruct;
- (void)dealloc;
- (id)accessibilityValue;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_touchUp:(id)arg1 event:(id)arg2;
- (void)_longPress:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)newDisplayText;
- (void)colorThemeDidChange;
- (void)setFont:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

