//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotMedium.h"

@class NSDate, NSObject<OS_dispatch_queue>, NSString;

@interface PTHTweetbotPostDraftMedium : PTHTweetbotMedium
{
    NSObject<OS_dispatch_queue> *_queue;
    long long _mediumTID;
    NSDate *_uploadDate;
    _Bool _isAnimatedGIF;
    NSString *_guid;
}

+ (void)initialize;
+ (id)newURLForMediumType:(long long)arg1;
@property(readonly, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(nonatomic) _Bool isAnimatedGIF; // @synthesize isAnimatedGIF=_isAnimatedGIF;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)delete;
@property(nonatomic) long long mediumTID;
- (void)loadDataForUpload:(CDUnknownBlockType)arg1;
- (void)loadURL:(CDUnknownBlockType)arg1;
- (void)loadPreviewURLWithSize:(unsigned long long)arg1 response:(CDUnknownBlockType)arg2;
- (void)loadPreviewImageWithSize:(struct CGSize)arg1 maxScale:(double)arg2 mode:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 response:(CDUnknownBlockType)arg5;
- (void)saveImage:(id)arg1 type:(id)arg2 toURL:(id)arg3;
- (void)saveRepresentation:(id)arg1 toURL:(id)arg2;
- (void)saveImageWithImagePickerDictionary:(id)arg1 toURL:(id)arg2;
- (void)saveMovieWithImagePickerDictionary:(id)arg1 toURL:(id)arg2;
- (id)initWithALRepresentation:(id)arg1 alLibrary:(id)arg2;
- (id)initWithImagePickerDictionary:(id)arg1;
- (void)_setURL:(id)arg1;
- (id)init;

@end

