//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotObject.h"

@class NSString;

@interface PTHTweetbotCachedUser : PTHTweetbotObject
{
    NSString *_name;
    NSString *_screenName;
    NSString *_profileImageURLString;
}

@property(copy, nonatomic) NSString *profileImageURLString; // @synthesize profileImageURLString=_profileImageURLString;
@property(copy, nonatomic) NSString *screenName; // @synthesize screenName=_screenName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)profileImageURLForSize:(unsigned long long)arg1;
@property(readonly, nonatomic) NSString *displayName;
- (_Bool)isLoaded;

@end

