//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotObject.h"

@class NSString, PTHTweetbotCursor, PTHTweetbotUser;

@interface PTHTweetbotList : PTHTweetbotObject
{
    PTHTweetbotUser *_user;
    PTHTweetbotCursor *_statusesCursor;
    _Bool _private;
    NSString *_name;
    NSString *_slug;
    NSString *_fullName;
    NSString *_listDescription;
    long long _userTID;
    NSString *_userScreenName;
    long long _subscriberCount;
    long long _memberCount;
}

+ (void)createWithName:(id)arg1 privacy:(_Bool)arg2 description:(id)arg3 forAccount:(id)arg4 result:(CDUnknownBlockType)arg5;
@property(nonatomic) long long memberCount; // @synthesize memberCount=_memberCount;
@property(nonatomic) long long subscriberCount; // @synthesize subscriberCount=_subscriberCount;
@property(nonatomic, getter=isPrivate) _Bool private; // @synthesize private=_private;
@property(copy, nonatomic) NSString *userScreenName; // @synthesize userScreenName=_userScreenName;
@property(nonatomic) long long userTID; // @synthesize userTID=_userTID;
@property(copy, nonatomic) NSString *listDescription; // @synthesize listDescription=_listDescription;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(copy, nonatomic) NSString *slug; // @synthesize slug=_slug;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setAccount:(id)arg1;
- (long long)compare:(id)arg1;
- (void)checkMembership:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)removeMember:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)addMember:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)checkSubscription:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)unsubscribe:(CDUnknownBlockType)arg1;
- (void)subscribe:(CDUnknownBlockType)arg1;
- (void)destroy:(CDUnknownBlockType)arg1;
- (void)refresh:(CDUnknownBlockType)arg1;
- (id)queryDictionary;
@property(readonly, nonatomic) PTHTweetbotCursor *subscribersCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *membersCursor;
@property(readonly, nonatomic) PTHTweetbotCursor *statusesCursor;
@property(readonly, nonatomic) PTHTweetbotUser *user;
@property(readonly, nonatomic) _Bool isFromCurrentUser;
- (void)updateFromDictionary:(id)arg1;
- (void)updateListWithName:(id)arg1 privacy:(_Bool)arg2 description:(id)arg3 result:(CDUnknownBlockType)arg4;
- (id)initWithUser:(id)arg1 slug:(id)arg2;

@end

