//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotUserCursor.h"

@interface PTHTweetbotUserTimelineCursor : PTHTweetbotUserCursor
{
    unsigned long long _fetchCount;
}

+ (Class)itemClass;
@property(nonatomic) unsigned long long fetchCount; // @synthesize fetchCount=_fetchCount;
- (id)queryDictionary;
- (id)requestURLString;
- (_Bool)usesTIDPagination;
- (_Bool)hasReadStatus;
- (id)initWithAccount:(id)arg1;

@end

