//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PTHTweetbotCell.h"

@class PTHHitInsetButton, PTHTweetbotPlace, UILabel;

@interface PTHTweetbotGeoCell : PTHTweetbotCell
{
    UILabel *_nameLabel;
    UILabel *_addressLabel;
    PTHHitInsetButton *_locationButton;
}

+ (double)cellHeightWithItem:(id)arg1 forTableView:(id)arg2;
+ (void)initialize;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)colorThemeDidChange;
- (void)showPlace:(id)arg1;
- (void)selectPlace;
- (void)setItem:(id)arg1;
@property(readonly, nonatomic) PTHTweetbotPlace *place;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

