//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDownloadDelegate.h"

@class NSData, NSDictionary, NSError, NSHTTPURLResponse, NSMutableData, NSMutableDictionary, NSObject<OS_dispatch_semaphore>, NSString, NSURL, NSURLCredential, NSURLRequest, NSURLSession, NSURLSessionTask, PTHURLRequestMimePostData;

@interface PTHURLRequest : NSObject <NSURLSessionDownloadDelegate>
{
    NSURLSession *_session;
    NSURLSessionTask *_sessionTask;
    NSObject<OS_dispatch_semaphore> *_synchronousSemaphore;
    NSMutableData *_responseData;
    NSHTTPURLResponse *_response;
    CDUnknownBlockType _responseBlock;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _streamBlock;
    _Bool _startedOnMain;
    NSMutableDictionary *_debugDictionary;
    unsigned long long _backgroundTaskIdentifier;
    _Bool _busy;
    _Bool _cookiesEnabled;
    _Bool _networkActivityEnabled;
    _Bool _continueInBackground;
    NSURL *_url;
    unsigned long long _responseType;
    NSDictionary *_postDictionary;
    PTHURLRequestMimePostData *_mimePostData;
    NSData *_postData;
    unsigned long long _postContentType;
    NSDictionary *_queryDictionary;
    NSDictionary *_headerDictionary;
    unsigned long long _requestMethod;
    double _timeoutIntervalForRequest;
    double _timeoutIntervalForResource;
    NSError *_error;
    NSURLCredential *_credential;
    NSString *_filename;
    NSString *_username;
    NSString *_password;
    NSURLRequest *_urlRequest;
}

+ (id)systemInformation;
+ (id)networkErrorWithStatusCode:(long long)arg1;
+ (id)decodingError;
+ (id)userCancelledError;
+ (id)timeoutError;
+ (id)busyError;
@property(nonatomic) _Bool continueInBackground; // @synthesize continueInBackground=_continueInBackground;
@property(nonatomic, getter=isNetworkActivityEnabled) _Bool networkActivityEnabled; // @synthesize networkActivityEnabled=_networkActivityEnabled;
@property(retain, nonatomic) NSURLRequest *urlRequest; // @synthesize urlRequest=_urlRequest;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
@property(retain, nonatomic) NSURLCredential *credential; // @synthesize credential=_credential;
@property(nonatomic) _Bool cookiesEnabled; // @synthesize cookiesEnabled=_cookiesEnabled;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) double timeoutIntervalForResource; // @synthesize timeoutIntervalForResource=_timeoutIntervalForResource;
@property(nonatomic) double timeoutIntervalForRequest; // @synthesize timeoutIntervalForRequest=_timeoutIntervalForRequest;
@property(nonatomic) unsigned long long requestMethod; // @synthesize requestMethod=_requestMethod;
@property(copy, nonatomic) NSDictionary *headerDictionary; // @synthesize headerDictionary=_headerDictionary;
@property(copy, nonatomic) NSDictionary *queryDictionary; // @synthesize queryDictionary=_queryDictionary;
@property(nonatomic) unsigned long long postContentType; // @synthesize postContentType=_postContentType;
@property(copy, nonatomic) NSData *postData; // @synthesize postData=_postData;
@property(copy, nonatomic) PTHURLRequestMimePostData *mimePostData; // @synthesize mimePostData=_mimePostData;
@property(copy, nonatomic) NSDictionary *postDictionary; // @synthesize postDictionary=_postDictionary;
@property(nonatomic) unsigned long long responseType; // @synthesize responseType=_responseType;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic, getter=isBusy) _Bool busy; // @synthesize busy=_busy;
- (void).cxx_destruct;
- (id)description;
- (void)_didFinish;
- (id)newValueFromData:(id)arg1 error:(id *)arg2;
- (void)cancel;
@property(readonly, nonatomic) NSHTTPURLResponse *response;
- (void)URLSession:(id)arg1 task:(id)arg2 didReceiveChallenge:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 willCacheResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didWriteData:(long long)arg3 totalBytesWritten:(long long)arg4 totalBytesExpectedToWrite:(long long)arg5;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didResumeAtOffset:(long long)arg3 expectedTotalBytes:(long long)arg4;
- (void)URLSession:(id)arg1 downloadTask:(id)arg2 didFinishDownloadingToURL:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)startStreaming:(CDUnknownBlockType)arg1 response:(CDUnknownBlockType)arg2;
- (void)startSynchronous:(CDUnknownBlockType)arg1;
- (void)startSynchronousWithProgress:(CDUnknownBlockType)arg1 response:(CDUnknownBlockType)arg2;
- (void)start:(CDUnknownBlockType)arg1;
- (void)startWithProgress:(CDUnknownBlockType)arg1 response:(CDUnknownBlockType)arg2;
- (_Bool)_startSynchronous:(_Bool)arg1;
- (void)addSystemInformation;
@property(readonly, nonatomic) NSURL *urlWithParams;
@property(readonly, nonatomic) NSString *requestMethodString;
@property(readonly, nonatomic) NSMutableDictionary *debugDictionary;
- (id)init;

@end

