//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSMapTable, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSOutputStream;

@interface PTHUIImageStartupCache : NSObject
{
    NSData *_readData;
    NSDictionary *_readInfo;
    NSMapTable *_readCache;
    struct CGColorSpace *_imageColorSpaceRef;
    NSOutputStream *_writeStream;
    NSMutableDictionary *_writeInfo;
    NSObject<OS_dispatch_queue> *_writeQueue;
    _Bool _writeDirty;
    unsigned long long _writeOffset;
}

+ (void)setIgnoreNames:(id)arg1;
+ (void)setCacheCount:(unsigned long long)arg1;
+ (void)reset;
+ (void)setup;
- (void).cxx_destruct;
- (void)dealloc;
- (void)_saveIfDirty;
- (void)addImageIfNeeded:(id)arg1 named:(id)arg2;
- (id)imageNamed:(id)arg1;
- (id)infoPath;
- (id)dataPath;
- (void)_reset;
- (id)init;

@end

