//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class UIButton;

@interface UIBarButtonItem (PTHUIBarButtonItemCategory)
+ (id)blankItem;
@property(readonly, nonatomic) UIButton *button;
@end

