//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@interface UIControl (PTHUIControlCategory)
+ (void)playTap;
+ (void)deselectAll:(id)arg1;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)addScrollViewTouchDownHack;
- (void)___touchDownHack:(id)arg1;
- (void)playTap;
- (void)removeTapSound;
- (void)addTapSound;
- (void)removeSound:(id)arg1;
- (void)addSound:(id)arg1;
- (void)removeBlockTarget:(id)arg1 forControlEvents:(unsigned long long)arg2;
- (id)addBlockTargetForControlEvents:(unsigned long long)arg1 block:(CDUnknownBlockType)arg2;
- (id)_blockTargetArray;
@end

