//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@class NSString;

@interface UIDevice (PTHUIDeviceCategory)
@property(readonly, nonatomic) _Bool isSlow;
@property(readonly, nonatomic) unsigned long long numberOfCores;
@property(readonly, retain, nonatomic) NSString *specificModel;
@property(readonly, nonatomic) unsigned long long systemVersionNumber;
@property(readonly, nonatomic) unsigned long long systemMegabytes;
@property(readonly, nonatomic) long long validOrientation;
@end

