//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFont.h"

@interface UIFont (PTHUIFontCategory)
+ (id)customBoldFontOfSize:(double)arg1;
+ (id)customFontOfSize:(double)arg1;
+ (void)setCustomFontDescriptorHandler:(CDUnknownBlockType)arg1;
+ (id)customFontWithDescriptor:(id)arg1 size:(double)arg2;
+ (id)preferredFontForCustomTextStyle:(id)arg1;
- (struct __CTFont *)CTFont;
@end

