//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIFontDescriptor.h"

@interface UIFontDescriptor (PTHUIFontDescriptorCategory)
+ (id)helveticaNeueInterfaceDescriptor;
+ (id)preferredCustomFontDescriptorSizedForTextStyle:(id)arg1;
+ (id)preferredFontDescriptorWithCustomTextStyle:(id)arg1;
+ (void)registerCustomTextStyle:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)customFontFamilyDescriptor;
+ (void)setDefaultFontFamilyDescriptor:(id)arg1;
+ (void)initialize;
- (id)fontDescriptorWithCustomFont;
- (id)fontDescriptorByDeletingAttributes:(id)arg1;
@end

