//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (PTHUIImageCategory)
+ (id)newAnimationFromImageSource:(struct CGImageSource *)arg1;
+ (id)newScaledImageFromData:(id)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4;
+ (id)newScaledImageFromURL:(id)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4;
+ (id)newScaledImageFromImage:(id)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4;
+ (id)newScaledImageFromImageSource:(struct CGImageSource *)arg1 size:(struct CGSize)arg2 maxScale:(double)arg3 mode:(unsigned long long)arg4;
+ (long long)orientationFromImageOrientation:(unsigned long long)arg1;
+ (id)platformImageNamed:(id)arg1;
+ (id)cachedImageNamed:(id)arg1 addUsingBlock:(CDUnknownBlockType)arg2;
+ (id)cachedImageNamed:(id)arg1;
+ (id)cachedAndDeserializedImageNamed:(id)arg1;
+ (void)cleanupForBackground;
+ (id)imageCache;
- (id)newOptimizedRawData;
- (id)initWithOptimizedRawData:(id)arg1 offset:(unsigned long long)arg2;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)stretchableImage;
- (id)imageWithOrientation:(long long)arg1;
- (id)newImageWithOrientation:(long long)arg1;
- (id)imageFromRect:(struct CGRect)arg1;
- (id)newImageFromRect:(struct CGRect)arg1;
- (id)splitHorizontally:(unsigned long long)arg1;
- (id)imageWithTintColor:(id)arg1;
- (id)imageWithScale:(double)arg1;
- (id)imageWithSize:(struct CGSize)arg1;
- (id)resizedImageWithSize:(struct CGSize)arg1;
- (id)imageByDeserializing;
@property(readonly, nonatomic) _Bool isOpaque;
- (id)imageByReplacingColor:(id)arg1 toColor:(id)arg2;
- (id)_imageByColoringAlpha:(id)arg1;
- (void)drawAtCenteredPoint:(struct CGPoint)arg1;
- (id)imageByFixingOrientation;
- (id)initWithContentsOf2xFile:(id)arg1;
- (void)addToCache:(id)arg1;
@end

