//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationBar.h"

@class NSString;

@interface UINavigationBar (PTHUINavigationBarColorNameCategory)
- (void)colorThemeDidChange;
@property(copy, nonatomic) NSString *titleTextColorName;
@property(copy, nonatomic) NSString *barTintColorName;
@end

