//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (PTHUITableViewCategory)
- (void)updateSection:(long long)arg1 fromArray:(id)arg2 toArray:(id)arg3;
- (void)updateSection:(long long)arg1 fromArray:(id)arg2 toArray:(id)arg3 withRowAnimation:(long long)arg4;
- (void)updateSection:(long long)arg1 fromArray:(id)arg2 toArray:(id)arg3 useIsEqual:(_Bool)arg4 withRowAnimation:(long long)arg5;
@end

