//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarItem.h"

@class UIImage;

@interface UITabBarItem (PTHTweetbotAccountControllerTabItemCategory)
@property(retain, nonatomic) UIImage *originalImage;
@property(nonatomic, getter=isRead) _Bool read;
@property(nonatomic) SEL doubleTapAction;
@end

