//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@interface UITextField (PTHUITextFieldCategory)
@property(copy, nonatomic) CDUnknownBlockType preferredTextStyleBlock;
- (void)setPreferredTextStyle:(id)arg1;
@end

