//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PTHTweetbotMediaControllerCategory)
- (void)presentMedia:(id)arg1 selectedMediumIndex:(unsigned long long)arg2 fromRect:(struct CGRect)arg3 inView:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)presentMedia:(id)arg1 selectedMediumIndex:(unsigned long long)arg2 accessoryView:(id)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)_presentImageMedia:(id)arg1 selectedMediumIndex:(unsigned long long)arg2 accessoryView:(id)arg3 fromRect:(struct CGRect)arg4 inView:(id)arg5 completion:(CDUnknownBlockType)arg6;
@end

