//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSString;

@interface UIViewController (PTHNavigationControllerCategory)
- (void)presentWithNavigationController:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) NSString *modalCancelButtonTitle;
- (void)ok:(id)arg1;
- (void)back:(id)arg1;
@end

