//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface UIView (PTHUIViewCategory)
+ (void)disabledAnimationBlock:(CDUnknownBlockType)arg1;
- (id)commonAnscestor:(id)arg1;
- (struct CGAffineTransform)transformToView:(id)arg1;
- (struct CGAffineTransform)_transformToParentView:(id)arg1;
- (void)updateShadowPath;
- (void)_removeFromCacheWindow;
- (void)cacheDraw;
- (void)unhide;
- (void)hide;
- (void)hideAndRemove;
@property(readonly, copy, nonatomic) NSArray *allSubviews;
- (void)ensureMinimumWidthMoveLeft:(double)arg1;
- (void)ensureMinimumWidth:(double)arg1;
- (void)makeFrameEvenMoveLeft;
- (void)makeFrameEven;
- (void)makeFrameIntegral;
- (void)centerIntegralY;
- (void)centerIntegralX;
- (void)centerIntegral;
- (struct CGPoint)centerPointInView:(id)arg1;
- (id)newImageView;
- (void)snapshotTransition:(CDUnknownBlockType)arg1;
- (void)snapshotTransitionWithDuration:(double)arg1 animations:(CDUnknownBlockType)arg2;
- (void)snapshotTransitionWithDuration:(double)arg1 options:(unsigned long long)arg2 animations:(CDUnknownBlockType)arg3;
- (id)getImage;
- (id)snapshotImageAfterScreenUpdates:(_Bool)arg1;
@property(readonly, nonatomic) double maxY;
@property(readonly, nonatomic) double maxX;
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) double y;
@property(nonatomic) double x;
@property(nonatomic) struct CGSize size;
@property(nonatomic) struct CGPoint origin;
@end

