//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableDictionary;

@interface UIView (PTHConstraintsCategory)
- (id)addRowConstraints:(id)arg1;
- (id)addRowConstraints:(id)arg1 padding:(double)arg2;
- (id)addColumnConstraints:(id)arg1;
- (id)addColumnConstraints:(id)arg1 padding:(double)arg2;
- (id)addLeftToRightConstraints:(id)arg1;
- (id)addLeftToRightConstraints:(id)arg1 padding:(double)arg2;
- (id)addTopToBottomConstraints:(id)arg1;
- (id)addTopToBottomConstraints:(id)arg1 padding:(double)arg2;
- (id)addFixedHeightConstraint:(double)arg1;
- (id)addFixedWidthConstraint:(double)arg1;
- (id)addFixedBottomConstraint:(double)arg1;
- (id)addFixedTopConstraint:(double)arg1;
- (id)addFixedRightConstraint:(double)arg1;
- (id)addFixedLeftConstraint:(double)arg1;
- (id)addFixedFrameConstraint:(struct CGRect)arg1;
- (id)addFixedSizeConstraint:(struct CGSize)arg1;
- (id)addFixedOriginConstraint:(struct CGPoint)arg1;
- (id)addEqualBaselineConstraints:(id)arg1;
- (id)addEqualBaselineConstraint:(id)arg1;
- (id)addEqualCenterYConstraints:(id)arg1;
- (id)addEqualCenterYConstraint:(id)arg1;
- (id)addEqualCenterXConstraints:(id)arg1;
- (id)addEqualCenterXConstraint:(id)arg1;
- (id)addEqualHeightConstraints:(id)arg1;
- (id)addEqualFrameConstraints:(id)arg1;
- (id)addEqualSizeConstraints:(id)arg1;
- (id)addEqualHeightConstraint:(id)arg1;
- (id)addEqualWidthConstraints:(id)arg1;
- (id)addEqualWidthConstraint:(id)arg1;
- (id)addEqualBottomConstraints:(id)arg1;
- (id)addEqualBottomConstraint:(id)arg1;
- (id)addEqualTopConstraints:(id)arg1;
- (id)addEqualTopConstraint:(id)arg1;
- (id)addEqualRightConstraints:(id)arg1;
- (id)addEqualRightConstraint:(id)arg1;
- (id)addEqualLeftConstraints:(id)arg1;
- (id)addEqualLeftConstraint:(id)arg1;
- (id)_addEqualConstraints:(id)arg1 attribute:(long long)arg2;
- (id)addInsetConstraint:(struct UIEdgeInsets)arg1;
- (id)addVerticallyPaddedConstraint:(double)arg1;
- (id)addVerticallyFittedConstraint;
- (id)addVerticallyCenteredConstraint;
- (id)addHorizontallyPaddedConstraint:(double)arg1;
- (id)addHorizontallyFittedConstraint;
- (id)addHorizontallyCenteredConstraint;
- (void)resumeConstraints;
- (void)pauseConstraints;
- (void)enableHideConstraints;
- (void)enableShowConstraints;
@property(retain, nonatomic) id showConstraints;
@property(retain, nonatomic) id hideConstraints;
- (id)constraintsNamed:(id)arg1;
- (id)constraintNamed:(id)arg1;
- (_Bool)isNamedConstraintEnabled:(id)arg1;
- (void)enableConstraintsNamed:(id)arg1;
- (void)disableConstraintsNamed:(id)arg1;
@property(readonly, nonatomic) NSMutableDictionary *namedConstraints;
@end

