//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (PTHUIViewControllerCategory)
+ (void)load;
- (void)presentViewController:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)pthDismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)pthViewDidDisappear:(_Bool)arg1;
- (void)pthViewWillDisappear:(_Bool)arg1;
- (void)pthViewDidAppear:(_Bool)arg1;
- (void)pthViewWillAppear:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isVisible;
@property(nonatomic) _Bool globalRotationDisabled;
@end

